import assert from 'node:assert/strict'
import {describe, it} from 'node:test'
import {
    allocateNextCivilianCallsign,
    formatCivilianCallsign,
    getCallsignValidationError,
    isAlphanumericCallsign,
    isAutoGeneratedCallsign,
    isCallsignTakenByOtherTrack,
    normalizeCallsignForComparison,
    sanitizeCallsignInput,
} from '../../app/tools/formatting/callsignValidation.js'

describe('callsignValidation', () => {
    describe('sanitizeCallsignInput', () => {
        it('removes non-alphanumeric characters', () => {
            assert.equal(sanitizeCallsignInput('EAGLE-01'), 'EAGLE01')
            assert.equal(sanitizeCallsignInput('trk 123'), 'trk123')
            assert.equal(sanitizeCallsignInput('ABC_9'), 'ABC9')
        })

        it('returns an empty string for empty input', () => {
            assert.equal(sanitizeCallsignInput(''), '')
            assert.equal(sanitizeCallsignInput(null), '')
        })
    })

    describe('isAlphanumericCallsign', () => {
        it('accepts letters and numbers only', () => {
            assert.equal(isAlphanumericCallsign('EAGLE01'), true)
            assert.equal(isAlphanumericCallsign('abc123'), true)
            assert.equal(isAlphanumericCallsign('CIV01'), true)
        })

        it('rejects empty or invalid callsigns', () => {
            assert.equal(isAlphanumericCallsign(''), false)
            assert.equal(isAlphanumericCallsign('FLT-1'), false)
            assert.equal(isAlphanumericCallsign('EAGLE 01'), false)
        })
    })

    describe('isCallsignTakenByOtherTrack', () => {
        const tracks = [
            {trackId: 'TRK-1', callsign: 'EAGLE01'},
            {trackId: 'TRK-2', callsign: 'HAWK12'},
        ]

        it('detects duplicate callsigns case-insensitively', () => {
            assert.equal(isCallsignTakenByOtherTrack('eagle01', tracks, 'TRK-2'), true)
            assert.equal(isCallsignTakenByOtherTrack('EAGLE01', tracks, 'TRK-1'), false)
            assert.equal(isCallsignTakenByOtherTrack('FALCON9', tracks, 'TRK-1'), false)
        })
    })

    describe('formatCivilianCallsign', () => {
        it('zero-pads civilian callsign numbers to two digits', () => {
            assert.equal(formatCivilianCallsign(1), 'CIV01')
            assert.equal(formatCivilianCallsign(12), 'CIV12')
            assert.equal(formatCivilianCallsign(100), 'CIV100')
        })
    })

    describe('allocateNextCivilianCallsign', () => {
        it('returns the lowest unused civilian callsign number', () => {
            const tracks = [
                {trackId: 'TRK-1', callsign: 'CIV01'},
                {trackId: 'TRK-2', callsign: 'CIV03'},
            ]

            assert.equal(allocateNextCivilianCallsign(tracks, 'TRK-3'), 'CIV02')
        })

        it('starts at CIV01 when no civilian callsigns exist', () => {
            assert.equal(allocateNextCivilianCallsign([], 'TRK-1'), 'CIV01')
        })
    })

    describe('isAutoGeneratedCallsign', () => {
        it('recognizes civilian and legacy auto callsign formats', () => {
            assert.equal(isAutoGeneratedCallsign('CIV01'), true)
            assert.equal(isAutoGeneratedCallsign('FLT-1'), true)
            assert.equal(isAutoGeneratedCallsign('TRKradarabc'), true)
            assert.equal(isAutoGeneratedCallsign('EAGLE01'), false)
        })
    })

    describe('getCallsignValidationError', () => {
        const tracks = [{trackId: 'TRK-1', callsign: 'EAGLE01'}]

        it('returns a format error for invalid callsigns', () => {
            assert.match(
                getCallsignValidationError('', tracks, 'TRK-2'),
                /letters and numbers/i,
            )
            assert.match(
                getCallsignValidationError('EAGLE-01', tracks, 'TRK-2'),
                /letters and numbers/i,
            )
        })

        it('returns a duplicate error when another track uses the callsign', () => {
            assert.match(
                getCallsignValidationError('EAGLE01', tracks, 'TRK-2'),
                /already in use/i,
            )
        })

        it('returns null for a valid unique callsign', () => {
            assert.equal(getCallsignValidationError('FALCON9', tracks, 'TRK-2'), null)
        })
    })

    describe('normalizeCallsignForComparison', () => {
        it('uppercases callsigns for comparison', () => {
            assert.equal(normalizeCallsignForComparison('eagle01'), 'EAGLE01')
        })
    })
})
