import {isAutoGeneratedCallsign} from '../tools/formatting/callsignValidation.js'

export const EMERGENCY_MODE3_CODES = ['7500', '7600', '7700']

export const EMERGENCY_ALARM_DEDUP_GRACE_MS = 300_000

export const MODE3_CODE_VFR_US = '1200'
export const MODE3_CODE_VFR_EU = '7000'

export const MIN_FLEET_EMERGENCY_COUNT = 1
export const MAX_FLEET_EMERGENCY_COUNT = 3

export const IFF_MODE3_STALE_MULTIPLIER = 3

/**
 * @param {string|null|undefined} code
 * @returns {boolean}
 */
export function isValidMode3Code(code) {
    if (typeof code !== 'string' || code.length === 0) {
        return false
    }

    const normalized = formatMode3Code(code)

    return normalized.length === 4 && /^[0-7]{4}$/.test(normalized)
}

/**
 * @param {string|number|null|undefined} code
 * @returns {string}
 */
export function formatMode3Code(code) {
    if (code === null || code === undefined) {
        return ''
    }

    return String(code).padStart(4, '0').slice(-4)
}

/**
 * @param {string|null|undefined} code
 * @returns {boolean}
 */
export function isEmergencyMode3Code(code) {
    return EMERGENCY_MODE3_CODES.includes(formatMode3Code(code))
}

/**
 * VFR block codes are shared by many aircraft and must not drive code-bound correlation.
 *
 * @param {string|null|undefined} code
 * @returns {boolean}
 */
export function isSharedVfrMode3Code(code) {
    const normalized = formatMode3Code(code)

    return normalized === MODE3_CODE_VFR_US || normalized === MODE3_CODE_VFR_EU
}

/**
 * @param {string|null|undefined} code
 * @returns {string|null}
 */
export function getEmergencyAttentionFlagId(code) {
    const normalized = formatMode3Code(code)

    if (normalized === '7700') {
        return 'IFF_EMER'
    }

    if (normalized === '7600') {
        return 'IFF_NORDO'
    }

    if (normalized === '7500') {
        return 'IFF_HIJ'
    }

    return null
}

/**
 * @param {string|null|undefined} code
 * @returns {string|null}
 */
export function getEmergencyAlertSignalId(code) {
    const normalized = formatMode3Code(code)

    if (normalized === '7700') {
        return 'IFF_EMER_ALERT'
    }

    if (normalized === '7600') {
        return 'IFF_NORDO_ALERT'
    }

    if (normalized === '7500') {
        return 'IFF_HIJ_ALERT'
    }

    return null
}

/**
 * @param {string|null|undefined} code
 * @returns {'EMERGENCY'|'NORDO'|'HIJACK'|null}
 */
export function getEmergencySquawkLabel(code) {
    const normalized = formatMode3Code(code)

    if (normalized === '7700') {
        return 'EMERGENCY'
    }

    if (normalized === '7600') {
        return 'NORDO'
    }

    if (normalized === '7500') {
        return 'HIJACK'
    }

    return null
}

/**
 * Stable dedup key for emergency IFF alarms. Prefers operator-assigned callsigns so
 * zoom-driven decorrelation does not retrigger the same squawk alert.
 *
 * @param {import('./types.js').TrackState} track
 * @param {string|null|undefined} mode3Code
 * @returns {string}
 */
export function buildIffEmergencyAlarmKey(track, mode3Code) {
    const normalizedCode = formatMode3Code(mode3Code)
    const trackId = track.trackId ?? track.id
    const callsign = track.callsign

    if (callsign && !isAutoGeneratedCallsign(callsign)) {
        return `${normalizedCode}:${callsign}`
    }

    return `${normalizedCode}:${trackId}`
}

/**
 * @param {import('./types.js').TrackState} track
 * @param {string|null|undefined} mode3Code
 * @returns {string}
 */
export function buildIffEmergencyAlarmMessage(track, mode3Code) {
    const callsign = track.callsign ?? track.trackId ?? track.id
    const squawkLabel = getEmergencySquawkLabel(mode3Code)

    return `Track (${callsign}) squawking ${squawkLabel ?? 'EMERGENCY'}`
}

/**
 * @param {() => number} random
 * @returns {string}
 */
export function pickRandomEmergencyMode3Code(random) {
    return EMERGENCY_MODE3_CODES[Math.floor(random() * EMERGENCY_MODE3_CODES.length)]
}

/**
 * @param {import('./types.js').TruthAircraftState} aircraft
 * @returns {{ vfr?: boolean, useEuropeanVfr?: boolean }}
 */
export function getMode3AssignmentOptionsForAircraft(aircraft) {
    if (aircraft?.trafficKind === 'generalAviation') {
        return {
            vfr: true,
            useEuropeanVfr: !String(aircraft.homeAirportIcao ?? '').startsWith('K'),
        }
    }

    return {vfr: false}
}

function normalizeFleetIterable(aircraft) {
    if (Array.isArray(aircraft)) {
        return aircraft
    }

    if (aircraft instanceof Map) {
        return Array.from(aircraft.values())
    }

    return Array.from(aircraft ?? [])
}

/**
 * @param {Iterable<import('./types.js').TruthAircraftState>|Map<string, import('./types.js').TruthAircraftState>} aircraft
 * @returns {number}
 */
export function countFleetEmergencySquawks(aircraft) {
    return normalizeFleetIterable(aircraft)
        .filter((item) => isEmergencyMode3Code(item.mode3Code))
        .length
}

/**
 * Keep the active fleet at a target of 1-3 emergency squawks (inclusive).
 *
 * @param {Iterable<import('./types.js').TruthAircraftState>|Map<string, import('./types.js').TruthAircraftState>} aircraft
 * @param {() => number} random
 * @param {{ minCount?: number, maxCount?: number, targetCount?: number }} [options]
 * @returns {{ targetCount: number, previousCount: number, nextCount: number }}
 */
export function maintainFleetEmergencySquawks(aircraft, random, options = {}) {
    const fleet = normalizeFleetIterable(aircraft)
    const fleetSize = fleet.length

    if (fleetSize === 0) {
        return {
            targetCount: 0,
            previousCount: 0,
            nextCount: 0,
        }
    }

    const minCount = options.minCount ?? MIN_FLEET_EMERGENCY_COUNT
    const maxCount = options.maxCount ?? MAX_FLEET_EMERGENCY_COUNT
    const effectiveMin = Math.min(minCount, fleetSize)
    const effectiveMax = Math.min(maxCount, fleetSize)
    const span = effectiveMax - effectiveMin + 1
    const targetCount = options.targetCount ?? (effectiveMin + Math.floor(random() * span))
    const emergencies = fleet.filter((item) => isEmergencyMode3Code(item.mode3Code))
    const nonEmergencies = fleet.filter((item) => !isEmergencyMode3Code(item.mode3Code))
    const previousCount = emergencies.length

    while (emergencies.length < targetCount && nonEmergencies.length > 0) {
        const index = Math.floor(random() * nonEmergencies.length)
        const selected = nonEmergencies.splice(index, 1)[0]

        selected.mode3Code = pickRandomEmergencyMode3Code(random)
        emergencies.push(selected)
    }

    while (emergencies.length > targetCount) {
        const index = Math.floor(random() * emergencies.length)
        const selected = emergencies.splice(index, 1)[0]

        selected.mode3Code = assignMode3Code(random, getMode3AssignmentOptionsForAircraft(selected))
        nonEmergencies.push(selected)
    }

    return {
        targetCount,
        previousCount,
        nextCount: emergencies.length,
    }
}

/**
 * @param {() => number} random
 * @param {{ vfr?: boolean, useEuropeanVfr?: boolean }} [options]
 * @returns {string}
 */
export function assignMode3Code(random, options = {}) {
    if (options.vfr) {
        return options.useEuropeanVfr ? MODE3_CODE_VFR_EU : MODE3_CODE_VFR_US
    }

    let code = ''

    do {
        code = Array.from({length: 4}, () => Math.floor(random() * 8)).join('')
    } while (EMERGENCY_MODE3_CODES.includes(code) || code === '0000')

    return code
}

/**
 * @param {import('./types.js').TrackState} track
 * @param {number} [evaluationTime]
 * @param {number} [iffRefreshMs]
 * @returns {boolean}
 */
export function isIffMode3Stale(track, evaluationTime = Date.now(), iffRefreshMs = 1000) {
    if (!track?.iffMode3Code) {
        return false
    }

    const updatedAt = track.iffMode3UpdatedAt ?? 0
    const staleThresholdMs = iffRefreshMs * IFF_MODE3_STALE_MULTIPLIER

    return evaluationTime - updatedAt > staleThresholdMs
}

/**
 * @param {string|null|undefined} code
 * @returns {string}
 */
export function getMode3DisplayLabel(code) {
    const normalized = formatMode3Code(code)

    return normalized || '—'
}
