import {haversineDistanceNm} from './geo'
import {TRACK_CORRELATION_MODES} from './trackFromDetection'

const MERGE_FIELDS = [
    'callsign',
    'domain',
    'identity',
    'type',
    'heading',
    'speed',
    'altitude',
    'infoFields',
    'correlationMode',
    'iconLabel',
    'useFamiliarIcon',
    'symbolOptions',
]

function isAutoGeneratedCallsign(callsign) {
    if (!callsign || typeof callsign !== 'string') {
        return true
    }

    return /^(TRK-|FLT-)/.test(callsign)
}

function fieldFromUserDirected(track, field) {
    if (!track?.userDirected) {
        return false
    }

    const value = track[field]

    if (field === 'infoFields') {
        return Boolean(value)
    }

    if (value === '' || value === null || value === undefined) {
        return false
    }

    if (field === 'callsign') {
        return !isAutoGeneratedCallsign(value)
    }

    return true
}

function pickMergedField(survivor, merged, field) {
    const survivorUser = fieldFromUserDirected(survivor, field)
    const mergedUser = fieldFromUserDirected(merged, field)

    if (survivorUser && mergedUser) {
        return survivor.lastUserEditAt >= merged.lastUserEditAt
            ? survivor[field]
            : merged[field]
    }

    if (mergedUser) {
        return merged[field]
    }

    if (survivorUser) {
        return survivor[field]
    }

    const survivorValue = survivor[field]
    const mergedValue = merged[field]

    if (survivorValue !== undefined && survivorValue !== null && survivorValue !== '') {
        return survivorValue
    }

    return mergedValue ?? survivorValue
}

export function findNearestActiveTrack(tracks, latitude, longitude, thresholdNm) {
    let bestTrack = null
    let bestDistance = Infinity

    tracks.forEach((track) => {
        if (track.correlationMode !== TRACK_CORRELATION_MODES.ACTIVE) {
            return
        }

        const distance = haversineDistanceNm(
            latitude,
            longitude,
            track.latitude,
            track.longitude,
        )

        if (distance <= thresholdNm && distance < bestDistance) {
            bestDistance = distance
            bestTrack = track
        }
    })

    return bestTrack
}

export function selectMergeSurvivor(tracks, trackStore) {
    if (!tracks.length) {
        return null
    }

    const manualTracks = tracks.filter((track) => trackStore.isManual(track.id))

    if (manualTracks.length > 0) {
        return manualTracks.sort((a, b) => (
            (b.lastUserEditAt ?? b.lastSensorUpdateAt ?? 0)
            - (a.lastUserEditAt ?? a.lastSensorUpdateAt ?? 0)
        ))[0]
    }

    const userEdited = tracks.filter((track) => track.userDirected)

    if (userEdited.length > 0) {
        return userEdited.sort((a, b) => (
            (b.lastUserEditAt ?? b.lastSensorUpdateAt ?? 0)
            - (a.lastUserEditAt ?? a.lastSensorUpdateAt ?? 0)
        ))[0]
    }

    return tracks.sort((a, b) => (
        (b.lastSensorUpdateAt ?? 0) - (a.lastSensorUpdateAt ?? 0)
    ))[0]
}

export function buildMergedTrackState(survivor, merged, timestamp) {
    const mergedState = {
        ...survivor,
        id: survivor.id,
        trackId: survivor.trackId ?? survivor.id,
    }

    MERGE_FIELDS.forEach((field) => {
        mergedState[field] = pickMergedField(survivor, merged, field)
    })

    if ((merged.lastSensorUpdateAt ?? 0) > (survivor.lastSensorUpdateAt ?? 0)) {
        mergedState.longitude = merged.longitude
        mergedState.latitude = merged.latitude
        mergedState.lastSensorUpdateAt = merged.lastSensorUpdateAt
        mergedState.lastExtrapolationAt = merged.lastExtrapolationAt ?? timestamp
        mergedState.correlated = Boolean(merged.correlated || survivor.correlated)
        mergedState.stale = false
    } else if (merged.correlated) {
        mergedState.correlated = true
    }

    if (merged.userDirected || survivor.userDirected) {
        mergedState.userDirected = true
        mergedState.lastUserEditAt = Math.max(
            merged.lastUserEditAt ?? 0,
            survivor.lastUserEditAt ?? 0,
        )
    }

    return mergedState
}

export function findProximityClusters(tracks, thresholdNm) {
    const activeTracks = tracks.filter((track) => (
        track.correlationMode === TRACK_CORRELATION_MODES.ACTIVE
    ))
    const clusters = []
    const assigned = new Set()

    activeTracks.forEach((seed) => {
        if (assigned.has(seed.id)) {
            return
        }

        const cluster = [seed]
        assigned.add(seed.id)

        activeTracks.forEach((other) => {
            if (assigned.has(other.id)) {
                return
            }

            const isNearCluster = cluster.some((member) => (
                haversineDistanceNm(
                    member.latitude,
                    member.longitude,
                    other.latitude,
                    other.longitude,
                ) <= thresholdNm
            ))

            if (isNearCluster) {
                cluster.push(other)
                assigned.add(other.id)
            }
        })

        if (cluster.length > 1) {
            clusters.push(cluster)
        }
    })

    return clusters
}

export function mergeProximityClusters(trackStore, thresholdNm, timestamp) {
    const clusters = findProximityClusters(trackStore.getAllTracks(), thresholdNm)
    const mergedAwayIds = []

    clusters.forEach((cluster) => {
        const survivor = selectMergeSurvivor(cluster, trackStore)

        if (!survivor) {
            return
        }

        cluster.forEach((track) => {
            if (track.id === survivor.id) {
                return
            }

            trackStore.mergeTracks(survivor.id, track.id, timestamp)
            mergedAwayIds.push(track.id)
        })
    })

    return mergedAwayIds
}
