import {haversineDistanceNm} from './geo.js'
import {formatMode3Code, isEmergencyMode3Code} from './iffMode3.js'
import {isAutoGeneratedCallsign} from '../tools/formatting/callsignValidation.js'
import {TRACK_CORRELATION_MODES} from './trackFromDetection.js'

const RECENCY_MERGE_FIELDS = ['callsign', 'type']

const PROPERTY_MERGE_FIELDS = [
    'domain',
    'identity',
    'specificType',
    'infoFields',
    'correlationMode',
    'iconLabel',
    'useFamiliarIcon',
    'symbolOptions',
]

function trackRecencyTimestamp(track) {
    return track.lastUserEditAt ?? track.lastSensorUpdateAt ?? 0
}

function fieldFromUserDirected(track, field) {
    if (!track?.userDirected) {
        return false
    }

    const value = track[field]

    if (field === 'infoFields') {
        return Boolean(value)
    }

    if (value === '' || value === null || value === undefined) {
        return false
    }

    if (field === 'callsign') {
        return !isAutoGeneratedCallsign(value)
    }

    return true
}

function pickMergedField(survivor, merged, field) {
    const survivorUser = fieldFromUserDirected(survivor, field)
    const mergedUser = fieldFromUserDirected(merged, field)

    if (survivorUser && mergedUser) {
        return survivor.lastUserEditAt >= merged.lastUserEditAt
            ? survivor[field]
            : merged[field]
    }

    if (mergedUser) {
        return merged[field]
    }

    if (survivorUser) {
        return survivor[field]
    }

    const survivorValue = survivor[field]
    const mergedValue = merged[field]

    if (survivorValue !== undefined && survivorValue !== null && survivorValue !== '') {
        return survivorValue
    }

    return mergedValue ?? survivorValue
}

function pickMostRecentField(survivor, merged, field) {
    const survivorUser = fieldFromUserDirected(survivor, field)
    const mergedUser = fieldFromUserDirected(merged, field)

    if (survivorUser && mergedUser) {
        return survivor.lastUserEditAt >= merged.lastUserEditAt
            ? survivor[field]
            : merged[field]
    }

    if (mergedUser) {
        return merged[field]
    }

    if (survivorUser) {
        return survivor[field]
    }

    return trackRecencyTimestamp(merged) > trackRecencyTimestamp(survivor)
        ? merged[field]
        : survivor[field]
}

function pickKinematicSource(survivor, merged) {
    if (merged.correlated && !survivor.correlated) {
        return merged
    }

    if (survivor.correlated && !merged.correlated) {
        return survivor
    }

    return (merged.lastSensorUpdateAt ?? 0) > (survivor.lastSensorUpdateAt ?? 0)
        ? merged
        : survivor
}

export function findNearestActiveTrack(tracks, latitude, longitude, thresholdNm) {
    let bestTrack = null
    let bestDistance = Infinity

    tracks.forEach((track) => {
        if (track.correlationMode !== TRACK_CORRELATION_MODES.ACTIVE) {
            return
        }

        const distance = haversineDistanceNm(
            latitude,
            longitude,
            track.latitude,
            track.longitude,
        )

        if (distance <= thresholdNm && distance < bestDistance) {
            bestDistance = distance
            bestTrack = track
        }
    })

    return bestTrack
}

export function selectMergeSurvivor(tracks, trackStore) {
    if (!tracks.length) {
        return null
    }

    const manualTracks = tracks.filter((track) => trackStore.isManual(track.id))

    if (manualTracks.length > 0) {
        return manualTracks.sort((a, b) => (
            (b.lastUserEditAt ?? b.lastSensorUpdateAt ?? 0)
            - (a.lastUserEditAt ?? a.lastSensorUpdateAt ?? 0)
        ))[0]
    }

    const userEdited = tracks.filter((track) => track.userDirected)

    if (userEdited.length > 0) {
        return userEdited.sort((a, b) => (
            (b.lastUserEditAt ?? b.lastSensorUpdateAt ?? 0)
            - (a.lastUserEditAt ?? a.lastSensorUpdateAt ?? 0)
        ))[0]
    }

    return tracks.sort((a, b) => (
        (b.lastSensorUpdateAt ?? 0) - (a.lastSensorUpdateAt ?? 0)
    ))[0]
}

export function normalizeTrackIdentity(identity) {
    return identity ?? 'pending'
}

export function tracksShareMergeIdentity(trackA, trackB) {
    return normalizeTrackIdentity(trackA?.identity) === normalizeTrackIdentity(trackB?.identity)
}

export function isActiveMergeCandidate(track) {
    return track?.correlationMode === TRACK_CORRELATION_MODES.ACTIVE
}

export function pickIffMergeSource(survivor, merged) {
    const survivorCode = formatMode3Code(survivor.iffMode3Code)
    const mergedCode = formatMode3Code(merged.iffMode3Code)
    const survivorEmergency = isEmergencyMode3Code(survivorCode)
    const mergedEmergency = isEmergencyMode3Code(mergedCode)

    if (survivorEmergency && !mergedEmergency) {
        return survivor
    }

    if (mergedEmergency && !survivorEmergency) {
        return merged
    }

    const survivorUpdatedAt = survivor.iffMode3UpdatedAt ?? 0
    const mergedUpdatedAt = merged.iffMode3UpdatedAt ?? 0

    return mergedUpdatedAt > survivorUpdatedAt ? merged : survivor
}

export function buildMergedTrackState(survivor, merged, timestamp) {
    const mergedState = {
        ...survivor,
        id: survivor.id,
        trackId: survivor.trackId ?? survivor.id,
    }

    RECENCY_MERGE_FIELDS.forEach((field) => {
        mergedState[field] = pickMostRecentField(survivor, merged, field)
    })

    PROPERTY_MERGE_FIELDS.forEach((field) => {
        mergedState[field] = pickMergedField(survivor, merged, field)
    })

    const kinematicSource = pickKinematicSource(survivor, merged)

    mergedState.heading = kinematicSource.heading ?? survivor.heading ?? 0
    mergedState.speed = kinematicSource.speed ?? survivor.speed ?? null
    mergedState.altitude = kinematicSource.altitude ?? survivor.altitude ?? null

    if ((kinematicSource.lastSensorUpdateAt ?? 0) >= (survivor.lastSensorUpdateAt ?? 0)) {
        mergedState.longitude = kinematicSource.longitude
        mergedState.latitude = kinematicSource.latitude
        mergedState.lastSensorUpdateAt = kinematicSource.lastSensorUpdateAt
        mergedState.lastExtrapolationAt = kinematicSource.lastExtrapolationAt ?? timestamp
        mergedState.correlated = Boolean(kinematicSource.correlated || survivor.correlated)
        mergedState.stale = false
    } else if (merged.correlated || survivor.correlated) {
        mergedState.correlated = true
    }

    if (merged.userDirected || survivor.userDirected) {
        mergedState.userDirected = true
        mergedState.lastUserEditAt = Math.max(
            merged.lastUserEditAt ?? 0,
            survivor.lastUserEditAt ?? 0,
        )
    }

    const iffSource = pickIffMergeSource(survivor, merged)

    if (iffSource.iffMode3Code) {
        mergedState.iffMode3Code = iffSource.iffMode3Code
        mergedState.iffMode3UpdatedAt = iffSource.iffMode3UpdatedAt ?? null
    } else {
        mergedState.iffMode3Code = null
        mergedState.iffMode3UpdatedAt = null
    }

    return mergedState
}

export function mergeTracksFromCorrelatedDetections(trackStore, correlatedDetections, thresholdNm, timestamp) {
    const correlatedTrackIds = new Set(
        correlatedDetections
            .filter((detection) => detection.correlated && detection.correlatedTrackId)
            .map((detection) => detection.correlatedTrackId),
    )
    const mergedAwayIds = []
    const pendingMergeIds = new Set()

    correlatedDetections.forEach((detection) => {
        if (!detection.correlated || !detection.correlatedTrackId) {
            return
        }

        const winner = trackStore.getTrack(detection.correlatedTrackId)

        if (!winner || !isActiveMergeCandidate(winner) || pendingMergeIds.has(winner.id)) {
            return
        }

        trackStore.getAllTracks().forEach((candidate) => {
            if (candidate.id === winner.id) {
                return
            }

            if (!isActiveMergeCandidate(candidate)) {
                return
            }

            if (pendingMergeIds.has(candidate.id)) {
                return
            }

            if (correlatedTrackIds.has(candidate.id)) {
                return
            }

            if (!tracksShareMergeIdentity(winner, candidate)) {
                return
            }

            const distanceToDetection = haversineDistanceNm(
                detection.latitude,
                detection.longitude,
                candidate.latitude,
                candidate.longitude,
            )

            if (distanceToDetection > thresholdNm) {
                return
            }

            const survivor = selectMergeSurvivor([winner, candidate], trackStore)

            if (!survivor) {
                return
            }

            const mergedId = survivor.id === winner.id ? candidate.id : winner.id

            trackStore.mergeTracks(survivor.id, mergedId, timestamp)
            pendingMergeIds.add(mergedId)
            mergedAwayIds.push(mergedId)
        })
    })

    return mergedAwayIds
}
