export const UI_Z_INDEX = {
    MAP: 0,
    MAP_OVERLAY: 1,
    MAP_PANEL: 10,
    TRACK_MANAGEMENT_WINDOW_BASE: 20,
    CONTEXT_MENU: 30,
    CLASSIFICATION_BAR: 100,
}

const MAX_TRACK_MANAGEMENT_WINDOW_STACK = UI_Z_INDEX.CONTEXT_MENU - UI_Z_INDEX.TRACK_MANAGEMENT_WINDOW_BASE - 1

export function getTrackManagementWindowZIndex(stackIndex) {
    return UI_Z_INDEX.TRACK_MANAGEMENT_WINDOW_BASE + Math.min(stackIndex, MAX_TRACK_MANAGEMENT_WINDOW_STACK)
}
