const ALPHANUMERIC_CALLSIGN_PATTERN = /^[A-Za-z0-9]+$/

export function sanitizeCallsignInput(value) {
    if (value === null || value === undefined) {
        return ''
    }

    return String(value).replace(/[^A-Za-z0-9]/g, '')
}

export function isAlphanumericCallsign(callsign) {
    return typeof callsign === 'string'
        && callsign.length > 0
        && ALPHANUMERIC_CALLSIGN_PATTERN.test(callsign)
}

export function normalizeCallsignForComparison(callsign) {
    if (callsign === null || callsign === undefined) {
        return ''
    }

    return String(callsign).toUpperCase()
}

export function getTrackCallsign(track) {
    return track?.callsign ?? track?.trackId ?? track?.id ?? ''
}

export function isCallsignTakenByOtherTrack(callsign, tracks, excludeTrackId) {
    const normalizedCallsign = normalizeCallsignForComparison(callsign)

    if (!normalizedCallsign) {
        return false
    }

    return tracks.some((track) => {
        const trackId = track.trackId ?? track.id

        if (!trackId || trackId === excludeTrackId) {
            return false
        }

        return normalizeCallsignForComparison(getTrackCallsign(track)) === normalizedCallsign
    })
}

export function formatCivilianCallsign(number) {
    return `CIV${String(number).padStart(2, '0')}`
}

export function getUsedCivilianCallsignNumbers(tracks, excludeTrackId) {
    const usedNumbers = new Set()

    tracks.forEach((track) => {
        const trackId = track.trackId ?? track.id

        if (!trackId || trackId === excludeTrackId) {
            return
        }

        const match = getTrackCallsign(track).match(/^CIV(\d+)$/i)

        if (match) {
            usedNumbers.add(Number(match[1]))
        }
    })

    return usedNumbers
}

export function allocateNextCivilianCallsign(tracks, excludeTrackId) {
    const usedNumbers = getUsedCivilianCallsignNumbers(tracks, excludeTrackId)
    let number = 1

    while (usedNumbers.has(number)) {
        number += 1
    }

    return formatCivilianCallsign(number)
}

export function isAutoGeneratedCallsign(callsign) {
    if (!callsign || typeof callsign !== 'string') {
        return true
    }

    if (/^CIV\d+$/i.test(callsign)) {
        return true
    }

    if (/^(TRK-|FLT-)/.test(callsign)) {
        return true
    }

    if (/^FLT\d+$/.test(callsign)) {
        return true
    }

    return /^TRK(radar|iff)/i.test(callsign)
}

export function getCallsignValidationError(callsign, tracks, excludeTrackId) {
    if (!isAlphanumericCallsign(callsign)) {
        return 'Callsign must contain only letters and numbers.'
    }

    if (isCallsignTakenByOtherTrack(callsign, tracks, excludeTrackId)) {
        return 'Callsign is already in use.'
    }

    return null
}

