import {platform, withUnspecified} from './helpers.js'

export const BOMBER_PLATFORMS = withUnspecified([
    platform('B-52H', 'B-52H Stratofortress'),
    platform('B-1B', 'B-1B Lancer'),
    platform('B-2A', 'B-2A Spirit'),
    platform('B-21', 'B-21 Raider'),
    platform('Tu-95MS', 'Tu-95MS Bear'),
    platform('Tu-95MSM', 'Tu-95MSM Bear'),
    platform('Tu-160', 'Tu-160 Blackjack'),
    platform('Tu-160M', 'Tu-160M Blackjack'),
    platform('Tu-22M3', 'Tu-22M3 Backfire'),
    platform('Tu-22M3M', 'Tu-22M3M Backfire'),
    platform('H-6', 'Xian H-6'),
    platform('H-6K', 'Xian H-6K'),
    platform('H-6N', 'Xian H-6N'),
    platform('H-6J', 'Xian H-6J'),
    platform('H-6M', 'Xian H-6M'),
    platform('H-20', 'Xian H-20'),
])

export const ATTACK_PLATFORMS = withUnspecified([
    platform('A-10C', 'A-10C Thunderbolt II'),
    platform('OA-1K', 'OA-1K Skyraider II'),
    platform('AC-130J', 'AC-130J Ghostrider'),
    platform('AC-130W', 'AC-130W Stinger II'),
    platform('AC-130U', 'AC-130U Spooky'),
    platform('Su-25', 'Su-25 Frogfoot'),
    platform('Su-25SM', 'Su-25SM Frogfoot'),
    platform('Su-25SM3', 'Su-25SM3 Frogfoot'),
    platform('Su-25UB', 'Su-25UB Frogfoot'),
    platform('Su-24M', 'Su-24M Fencer'),
    platform('Su-24M2', 'Su-24M2 Fencer'),
    platform('Su-24MR', 'Su-24MR Fencer'),
    platform('AV-8B', 'AV-8B Harrier II'),
    platform('AV-8B+', 'AV-8B+ Harrier II Plus'),
    platform('A-29', 'A-29 Super Tucano'),
    platform('EMB-314', 'EMB-314 Super Tucano'),
    platform('AT-6', 'Beechcraft AT-6 Wolverine'),
    platform('AT-802U', 'AT-802U Sky Warden'),
    platform('L-39ZA', 'Aero L-39ZA Albatros'),
])

export const FIGHTER_BOMBER_PLATFORMS = withUnspecified([
    platform('F-15E', 'F-15E Strike Eagle'),
    platform('F-15I', 'F-15I Ra\'am'),
    platform('F-15K', 'F-15K Slam Eagle'),
    platform('F-15S', 'F-15S Eagle'),
    platform('F-15SA', 'F-15SA Eagle'),
    platform('F-15QA', 'F-15QA Eagle'),
    platform('F-16C', 'F-16C Fighting Falcon'),
    platform('F-16D', 'F-16D Fighting Falcon'),
    platform('F-35A', 'F-35A Lightning II'),
    platform('Su-34', 'Su-34 Fullback'),
    platform('Su-34M', 'Su-34M Fullback'),
    platform('JH-7A', 'Xian JH-7A Flounder'),
    platform('JH-7B', 'Xian JH-7B Flounder'),
    platform('Tornado IDS', 'Panavia Tornado IDS'),
    platform('Tornado ECR', 'Panavia Tornado ECR'),
    platform('Tornado GR4', 'Panavia Tornado GR4'),
    platform('F-2A', 'Mitsubishi F-2A'),
    platform('F-2B', 'Mitsubishi F-2B'),
    platform('Rafale B', 'Dassault Rafale B'),
    platform('Rafale C', 'Dassault Rafale C'),
    platform('Rafale M', 'Dassault Rafale M'),
    platform('Typhoon', 'Eurofighter Typhoon'),
    platform('Gripen E', 'Saab JAS 39 Gripen E'),
    platform('Mirage 2000D', 'Dassault Mirage 2000D'),
    platform('Mirage 2000N', 'Dassault Mirage 2000N'),
    platform('Q-5', 'Nanchang Q-5 Fantan'),
    platform('Su-30MKI', 'Su-30MKI Flanker'),
    platform('Su-30SM', 'Su-30SM Flanker'),
    platform('J-16', 'Shenyang J-16'),
    platform('JF-17', 'JF-17 Thunder'),
    platform('KF-21', 'KAI KF-21 Boramae'),
    platform('FA-50', 'KAI FA-50 Fighting Eagle'),
])
