import {platform, withUnspecified} from './helpers.js'

export const CARGO_PLATFORMS = withUnspecified([
    // United States
    platform('C-5M', 'C-5M Super Galaxy'),
    platform('C-17A', 'C-17A Globemaster III'),
    platform('C-130H', 'C-130H Hercules'),
    platform('C-130J', 'C-130J Super Hercules'),
    platform('C-130J-30', 'C-130J-30 Super Hercules'),
    platform('C-27J', 'C-27J Spartan'),
    platform('C-2A', 'C-2A Greyhound'),
    platform('C-12', 'C-12 Huron'),
    platform('C-146A', 'C-146A Wolfhound'),
    platform('C-41', 'CASA C-41 Aviocar'),
    platform('CN-235', 'CASA CN-235'),
    platform('CMV-22B', 'CMV-22B Osprey'),
    platform('CV-22B', 'CV-22B Osprey'),
    platform('LC-130H', 'LC-130H Hercules'),
    platform('HC-130J', 'HC-130J Combat King II'),
    platform('MC-130J', 'MC-130J Commando II'),
    platform('WC-130J', 'WC-130J Hercules'),
    // Russia / Soviet
    platform('An-12', 'Antonov An-12 Cub'),
    platform('An-22', 'Antonov An-22 Antei'),
    platform('An-26', 'Antonov An-26 Curl'),
    platform('An-72', 'Antonov An-72 Coaler'),
    platform('An-124', 'Antonov An-124 Ruslan'),
    platform('An-140', 'Antonov An-140'),
    platform('An-148', 'Antonov An-148'),
    platform('Il-18', 'Ilyushin Il-18'),
    platform('Il-76', 'Ilyushin Il-76 Candid'),
    platform('Il-76MD', 'Ilyushin Il-76MD Candid'),
    platform('Il-76MD-90A', 'Ilyushin Il-76MD-90A'),
    platform('Tu-134', 'Tupolev Tu-134'),
    platform('Tu-154', 'Tupolev Tu-154'),
    platform('L-410', 'Let L-410 Turbolet'),
    // China
    platform('Y-20', 'Xian Y-20 Kunpeng'),
    platform('Y-20A', 'Xian Y-20A Kunpeng'),
    platform('Y-20B', 'Xian Y-20B Kunpeng'),
    platform('Y-9', 'Shaanxi Y-9'),
    platform('Y-8', 'Shaanxi Y-8'),
    platform('Y-7', 'Xian Y-7'),
    platform('Y-12', 'Harbin Y-12'),
    platform('Il-76-CN', 'Ilyushin Il-76 (China)'),
    // Europe
    platform('A400M', 'Airbus A400M Atlas'),
    platform('C-295', 'Airbus C-295'),
    platform('CN-235-EUR', 'CASA CN-235 (Europe)'),
    platform('C-390', 'Embraer C-390 Millennium'),
    platform('C-27J-EUR', 'C-27J Spartan (Europe)'),
    platform('Transall C-160', 'Transall C-160'),
    // Other NATO / allies
    platform('C-130H-TUR', 'C-130H Hercules (Turkey)'),
    platform('C-130J-NOR', 'C-130J Super Hercules (Norway)'),
    platform('C-130J-ISR', 'C-130J Super Hercules (Israel)'),
    platform('C-130J-EGY', 'C-130H Hercules (Egypt)'),
    platform('C-130J-KOR', 'C-130J Super Hercules (South Korea)'),
    platform('C-130J-JPN', 'C-130H Hercules (Japan)'),
    platform('C-130J-AUS', 'C-130J Super Hercules (Australia)'),
    platform('C-17-IND', 'C-17 Globemaster III (India)'),
    platform('C-17-QAT', 'C-17 Globemaster III (Qatar)'),
    platform('C-17-UAE', 'C-17 Globemaster III (UAE)'),
    platform('C-17-GBR', 'C-17 Globemaster III (UK)'),
    platform('C-2-JPN', 'Kawasaki C-2'),
    platform('An-32', 'Antonov An-32 Cline'),
    platform('An-32-IND', 'Antonov An-32 (India)'),
    platform('An-70', 'Antonov An-70'),
    platform('CASA 212', 'CASA 212 Aviocar'),
    platform('DHC-6', 'de Havilland Canada DHC-6 Twin Otter'),
    platform('PC-12', 'Pilatus PC-12'),
    platform('PC-24', 'Pilatus PC-24'),
    platform('Saab 340', 'Saab 340'),
    platform('Saab 2000', 'Saab 2000'),
    platform('ATR 72', 'ATR 72'),
    platform('An-178', 'Antonov An-178'),
    platform('KC-390', 'Embraer KC-390'),
    platform('C-130H-PAK', 'C-130B/E Hercules (Pakistan)'),
    platform('Y-20-PK', 'Xian Y-20 (export)'),
])
