import {platform, withUnspecified} from './helpers.js'

export const FIGHTER_PLATFORMS = withUnspecified([
    // United States
    platform('F-15C', 'F-15C Eagle'),
    platform('F-15D', 'F-15D Eagle'),
    platform('F-15EX', 'F-15EX Eagle II'),
    platform('F-16C', 'F-16C Fighting Falcon'),
    platform('F-16D', 'F-16D Fighting Falcon'),
    platform('F-16V', 'F-16V Fighting Falcon'),
    platform('F-22A', 'F-22A Raptor'),
    platform('F-35A', 'F-35A Lightning II'),
    platform('F-35B', 'F-35B Lightning II'),
    platform('F-35C', 'F-35C Lightning II'),
    platform('F/A-18C', 'F/A-18C Hornet'),
    platform('F/A-18D', 'F/A-18D Hornet'),
    platform('F/A-18E', 'F/A-18E Super Hornet'),
    platform('F/A-18F', 'F/A-18F Super Hornet'),
    platform('F-5E', 'F-5E Tiger II'),
    platform('F-5F', 'F-5F Tiger II'),
    platform('F-5N', 'F-5N Tiger II'),
    platform('QF-16', 'QF-16 Aerial Target'),
    // Russia
    platform('MiG-29', 'MiG-29 Fulcrum'),
    platform('MiG-29K', 'MiG-29K Fulcrum'),
    platform('MiG-29KUB', 'MiG-29KUB Fulcrum'),
    platform('MiG-29SMT', 'MiG-29SMT Fulcrum'),
    platform('MiG-29UB', 'MiG-29UB Fulcrum'),
    platform('MiG-31', 'MiG-31 Foxhound'),
    platform('MiG-31BM', 'MiG-31BM Foxhound'),
    platform('MiG-31K', 'MiG-31K Kinzhal Carrier'),
    platform('MiG-35', 'MiG-35 Fulcrum'),
    platform('Su-27', 'Su-27 Flanker'),
    platform('Su-27SM', 'Su-27SM Flanker'),
    platform('Su-27SM3', 'Su-27SM3 Flanker'),
    platform('Su-30', 'Su-30 Flanker'),
    platform('Su-30SM', 'Su-30SM Flanker'),
    platform('Su-30SM2', 'Su-30SM2 Flanker'),
    platform('Su-30MKI', 'Su-30MKI Flanker'),
    platform('Su-30MKK', 'Su-30MKK Flanker'),
    platform('Su-30MK2', 'Su-30MK2 Flanker'),
    platform('Su-30MKM', 'Su-30MKM Flanker'),
    platform('Su-30MKA', 'Su-30MKA Flanker'),
    platform('Su-33', 'Su-33 Flanker-D'),
    platform('Su-35S', 'Su-35S Flanker-E'),
    platform('Su-57', 'Su-57 Felon'),
    // China
    platform('J-7', 'Chengdu J-7'),
    platform('J-8', 'Shenyang J-8'),
    platform('J-8II', 'Shenyang J-8II'),
    platform('J-10', 'Chengdu J-10'),
    platform('J-10C', 'Chengdu J-10C'),
    platform('J-11', 'Shenyang J-11'),
    platform('J-11B', 'Shenyang J-11B'),
    platform('J-15', 'Shenyang J-15'),
    platform('J-16', 'Shenyang J-16'),
    platform('J-20', 'Chengdu J-20'),
    platform('J-35A', 'Shenyang J-35A'),
    platform('Su-27SK', 'Su-27SK Flanker (China)'),
    platform('Su-35S-CN', 'Su-35S (China)'),
    // Europe
    platform('Rafale B', 'Dassault Rafale B'),
    platform('Rafale C', 'Dassault Rafale C'),
    platform('Rafale M', 'Dassault Rafale M'),
    platform('Typhoon Tranche 1', 'Eurofighter Typhoon Tranche 1'),
    platform('Typhoon Tranche 2', 'Eurofighter Typhoon Tranche 2'),
    platform('Typhoon Tranche 3', 'Eurofighter Typhoon Tranche 3'),
    platform('Typhoon Tranche 4', 'Eurofighter Typhoon Tranche 4'),
    platform('Gripen C', 'Saab JAS 39 Gripen C'),
    platform('Gripen D', 'Saab JAS 39 Gripen D'),
    platform('Gripen E', 'Saab JAS 39 Gripen E'),
    platform('Gripen F', 'Saab JAS 39 Gripen F'),
    platform('Mirage 2000-5', 'Dassault Mirage 2000-5'),
    platform('Mirage 2000C', 'Dassault Mirage 2000C'),
    platform('Mirage 2000D', 'Dassault Mirage 2000D'),
    platform('Mirage F1', 'Dassault Mirage F1'),
    platform('Mirage III', 'Dassault Mirage III'),
    platform('Mirage 5', 'Dassault Mirage 5'),
    // India
    platform('Tejas Mk1', 'HAL Tejas Mk1'),
    platform('Tejas Mk1A', 'HAL Tejas Mk1A'),
    platform('MiG-29UPG', 'MiG-29UPG Fulcrum (India)'),
    // Japan
    platform('F-15J', 'Mitsubishi F-15J'),
    platform('F-15DJ', 'Mitsubishi F-15DJ'),
    platform('F-2A', 'Mitsubishi F-2A'),
    platform('F-2B', 'Mitsubishi F-2B'),
    platform('F-35A-JPN', 'F-35A Lightning II (Japan)'),
    // South Korea
    platform('F-4E', 'F-4E Phantom II (South Korea)'),
    platform('F-5E-KOR', 'F-5E Tiger II (South Korea)'),
    platform('F-15K', 'F-15K Slam Eagle'),
    platform('KF-21', 'KAI KF-21 Boramae'),
    platform('FA-50', 'KAI FA-50 Fighting Eagle'),
    platform('T-50', 'KAI T-50 Golden Eagle'),
    // Taiwan
    platform('F-CK-1C', 'AIDC F-CK-1C Ching-kuo'),
    platform('F-CK-1D', 'AIDC F-CK-1D Ching-kuo'),
    platform('F-16A-TW', 'F-16A Fighting Falcon (Taiwan)'),
    platform('F-16B-TW', 'F-16B Fighting Falcon (Taiwan)'),
    platform('F-16V-TW', 'F-16V Fighting Falcon (Taiwan)'),
    // Pakistan
    platform('JF-17 Block I', 'JF-17 Thunder Block I'),
    platform('JF-17 Block II', 'JF-17 Thunder Block II'),
    platform('JF-17 Block III', 'JF-17 Thunder Block III'),
    platform('J-10CE', 'Chengdu J-10CE (Pakistan)'),
    platform('F-7PG', 'Chengdu F-7PG (Pakistan)'),
    // Middle East
    platform('F-15S', 'F-15S Eagle (Saudi Arabia)'),
    platform('F-15SA', 'F-15SA Eagle (Saudi Arabia)'),
    platform('F-15QA', 'F-15QA Eagle (Qatar)'),
    platform('F-15I', 'F-15I Ra\'am (Israel)'),
    platform('F-15C-ISR', 'F-15C Baz (Israel)'),
    platform('F-15D-ISR', 'F-15D Baz (Israel)'),
    platform('F-16I', 'F-16I Sufa (Israel)'),
    platform('F-16C-EGY', 'F-16C Fighting Falcon (Egypt)'),
    platform('F-16C-TUR', 'F-16C Fighting Falcon (Turkey)'),
    platform('F-16C-UAE', 'F-16C Fighting Falcon (UAE)'),
    platform('Rafale EQ', 'Dassault Rafale EQ (Qatar)'),
    platform('Rafale DQ', 'Dassault Rafale DQ (Qatar)'),
    platform('Rafale UAE', 'Dassault Rafale (UAE)'),
    platform('Typhoon RSAF', 'Eurofighter Typhoon (Saudi Arabia)'),
    // NATO / Europe operators
    platform('F-16AM', 'F-16AM Fighting Falcon'),
    platform('F-16BM', 'F-16BM Fighting Falcon'),
    platform('F-16C-NATO', 'F-16C Fighting Falcon (NATO)'),
    platform('F-16D-NATO', 'F-16D Fighting Falcon (NATO)'),
    platform('F-35A-NOR', 'F-35A Lightning II (Norway)'),
    platform('F-35A-NLD', 'F-35A Lightning II (Netherlands)'),
    platform('F-35A-DNK', 'F-35A Lightning II (Denmark)'),
    platform('F-35A-BEL', 'F-35A Lightning II (Belgium)'),
    platform('F-35A-POL', 'F-35A Lightning II (Poland)'),
    platform('F-35A-CZE', 'F-35A Lightning II (Czech Republic)'),
    platform('F-35A-ITA', 'F-35A Lightning II (Italy)'),
    platform('F-35A-GBR', 'F-35A Lightning II (UK)'),
    platform('F-35B-GBR', 'F-35B Lightning II (UK)'),
    platform('F/A-18A', 'F/A-18A Hornet (Australia)'),
    platform('F/A-18B', 'F/A-18B Hornet (Australia)'),
    platform('F/A-18C-CAN', 'CF-18 Hornet (Canada)'),
    platform('F/A-18C-FIN', 'F/A-18C Hornet (Finland)'),
    platform('F/A-18C-ESP', 'EF-18 Hornet (Spain)'),
    platform('F/A-18C-SUI', 'F/A-18C Hornet (Switzerland)'),
    platform('F/A-18C-MYS', 'F/A-18D Hornet (Malaysia)'),
    // Other Asia-Pacific
    platform('F-16C-SGP', 'F-16C Fighting Falcon (Singapore)'),
    platform('F-16C-THA', 'F-16C Fighting Falcon (Thailand)'),
    platform('F-16C-IDN', 'F-16C Fighting Falcon (Indonesia)'),
    platform('F-16C-VNM', 'F-16C Fighting Falcon (Vietnam)'),
    platform('F-7', 'Chengdu F-7 (export)'),
    platform('F-7BGI', 'Chengdu F-7BGI (Bangladesh)'),
    // Latin America
    platform('F-5E-BRA', 'F-5E Tiger II (Brazil)'),
    platform('F-5E-CHL', 'F-5E Tiger III (Chile)'),
    platform('F-5E-MEX', 'F-5E Tiger II (Mexico)'),
    platform('Gripen E-BRA', 'Saab Gripen E (Brazil)'),
    platform('Kfir C10', 'IAI Kfir C10'),
    platform('Kfir C12', 'IAI Kfir C12'),
    // Iran
    platform('F-4E-IRN', 'F-4E Phantom II (Iran)'),
    platform('F-5E-IRN', 'F-5E Tiger II (Iran)'),
    platform('F-14A-IRN', 'F-14A Tomcat (Iran)'),
    platform('MiG-29-IRN', 'MiG-29 Fulcrum (Iran)'),
    platform('Saeqeh', 'HESA Saeqeh'),
    platform('Kowsar', 'HESA Kowsar'),
    platform('Azarakhsh', 'HESA Azarakhsh'),
    // Africa
    platform('Cheetah C', 'Atlas Cheetah C'),
    platform('Cheetah D', 'Atlas Cheetah D'),
    platform('Gripen C-ZAF', 'Saab Gripen C (South Africa)'),
    // North Korea
    platform('MiG-29-PRK', 'MiG-29 Fulcrum (North Korea)'),
    platform('MiG-23-PRK', 'MiG-23 Flogger (North Korea)'),
    platform('Su-25-PRK', 'Su-25 Frogfoot (North Korea)'),
])
