import {platform, withUnspecified} from './helpers.js'

export const SURFACE_COMBATANT_PLATFORMS = withUnspecified([
    // United States Navy
    platform('DDG-51', 'Arleigh Burke-class destroyer (DDG-51)'),
    platform('CG-47', 'Ticonderoga-class cruiser (CG-47)'),
    platform('FFG-62', 'Constellation-class frigate (FFG-62)'),
    platform('LCS-1', 'Freedom-class littoral combat ship'),
    platform('LCS-2', 'Independence-class littoral combat ship'),
    platform('DDG-1000', 'Zumwalt-class destroyer (DDG-1000)'),
    platform('LPD-17', 'San Antonio-class amphibious transport dock'),
    platform('LHA-6', 'America-class amphibious assault ship'),
    platform('LHD-1', 'Wasp-class amphibious assault ship'),
    platform('LCC-19', 'Blue Ridge-class command ship'),
    // United Kingdom
    platform('Type 45', 'Type 45 Daring-class destroyer'),
    platform('Type 26', 'Type 26 City-class frigate'),
    platform('Type 31', 'Type 31 Inspiration-class frigate'),
    platform('Type 23', 'Type 23 Duke-class frigate'),
    // France
    platform('Horizon', 'Horizon-class air defence destroyer'),
    platform('FREMM', 'FREMM multipurpose frigate'),
    platform('La Fayette', 'La Fayette-class frigate'),
    platform('Floreal', 'Floreal-class frigate'),
    // Germany
    platform('F124', 'Sachsen-class frigate (F124)'),
    platform('F125', 'Baden-Württemberg-class frigate (F125)'),
    platform('F122', 'Bremen-class frigate (F122)'),
    // Italy
    platform('FREMM-ITA', 'FREMM frigate (Italy)'),
    platform('Orizzonte', 'Orizzonte-class destroyer'),
    platform('Maestrale', 'Maestrale-class frigate'),
    // Spain
    platform('F100', 'Álvaro de Bazán-class frigate (F100)'),
    platform('F110', 'F110-class frigate'),
    // Netherlands
    platform('De Zeven Provinciën', 'De Zeven Provinciën-class frigate'),
    platform('Holland', 'Holland-class offshore patrol vessel'),
    // Russia
    platform('Admiral Gorshkov', 'Admiral Gorshkov-class frigate'),
    platform('Admiral Grigorovich', 'Admiral Grigorovich-class frigate'),
    platform('Admiral Kasatonov', 'Admiral Kasatonov-class frigate'),
    platform('Gepard', 'Gepard-class frigate'),
    platform('Neustrashimy', 'Neustrashimy-class frigate'),
    platform('Steregushchiy', 'Steregushchiy-class corvette'),
    platform('Gremyashchiy', 'Gremyashchiy-class corvette'),
    platform('Karakurt', 'Karakurt-class corvette'),
    platform('Buyan-M', 'Buyan-M-class corvette'),
    platform('Slava', 'Slava-class cruiser'),
    platform('Kirov', 'Kirov-class battlecruiser'),
    platform('Udaloy', 'Udaloy-class destroyer'),
    platform('Sovremenny', 'Sovremenny-class destroyer'),
    // China
    platform('Type 055', 'Type 055 Renhai-class cruiser'),
    platform('Type 052D', 'Type 052D Luyang III-class destroyer'),
    platform('Type 052C', 'Type 052C Luyang II-class destroyer'),
    platform('Type 051C', 'Type 051C Luzhou-class destroyer'),
    platform('Type 054A', 'Type 054A Jiangkai II-class frigate'),
    platform('Type 054B', 'Type 054B Jiangkai III-class frigate'),
    platform('Type 056A', 'Type 056A Jiangdao-class corvette'),
    platform('Type 022', 'Type 022 Houbei-class missile boat'),
    platform('Type 039A', 'Type 039A Yuan-class submarine (surface escort group)'),
    // Japan
    platform('Maya', 'Maya-class destroyer'),
    platform('Atago', 'Atago-class destroyer'),
    platform('Kongo', 'Kongo-class destroyer'),
    platform('Asahi', 'Asahi-class destroyer'),
    platform('Akizuki', 'Akizuki-class destroyer'),
    platform('Mogami', 'Mogami-class frigate'),
    // South Korea
    platform('Sejong the Great', 'Sejong the Great-class destroyer'),
    platform('Chungmugong Yi Sun-sin', 'Chungmugong Yi Sun-sin-class destroyer'),
    platform('Gwanggaeto', 'Gwanggaeto the Great-class destroyer'),
    platform('Daegu', 'Daegu-class frigate'),
    platform('Incheon', 'Incheon-class frigate'),
    // India
    platform('Visakhapatnam', 'Visakhapatnam-class destroyer'),
    platform('Kolkata', 'Kolkata-class destroyer'),
    platform('Delhi', 'Delhi-class destroyer'),
    platform('Talwar', 'Talwar-class frigate'),
    platform('Shivalik', 'Shivalik-class frigate'),
    // Australia
    platform('Hobart', 'Hobart-class destroyer'),
    platform('Anzac', 'Anzac-class frigate'),
    platform('Hunter', 'Hunter-class frigate'),
    // Turkey
    platform('Istanbul', 'Istanbul-class frigate'),
    platform('Ada', 'Ada-class corvette'),
    platform('Barbaros', 'Barbaros-class frigate'),
    // Other NATO / allies
    platform('Iver Huitfeldt', 'Iver Huitfeldt-class frigate (Denmark)'),
    platform('Absalon', 'Absalon-class frigate (Denmark)'),
    platform('Fridtjof Nansen', 'Fridtjof Nansen-class frigate (Norway)'),
    platform('Halifax', 'Halifax-class frigate (Canada)'),
    platform('River', 'River-class offshore patrol vessel (UK)'),
    platform('Kolkata-IND', 'Kolkata-class destroyer (India)'),
    platform('FREMM-EGY', 'FREMM frigate (Egypt)'),
    platform('Gowind', 'Gowind-class corvette'),
    platform('Sigma', 'Sigma-class corvette'),
    platform('Braunschweig', 'Braunschweig-class corvette (Germany)'),
    platform('K130', 'K130 Braunschweig-class corvette'),
    platform('MEKO 200', 'MEKO 200-class frigate'),
    platform('MEKO A-200', 'MEKO A-200-class frigate'),
    platform('Kang Ding', 'Kang Ding-class frigate (Taiwan)'),
    platform('Cheng Kung', 'Cheng Kung-class frigate (Taiwan)'),
    platform('Chi Yang', 'Chi Yang-class frigate (Taiwan)'),
    platform('Al Riyadh', 'Al Riyadh-class frigate (Saudi Arabia)'),
    platform('Al Madinah', 'Al Madinah-class frigate (Saudi Arabia)'),
    platform('Baynunah', 'Baynunah-class corvette (UAE)'),
    platform('Sa\'ar 5', 'Sa\'ar 5-class corvette (Israel)'),
    platform('Sa\'ar 6', 'Sa\'ar 6-class corvette (Israel)'),
])

export const SUBMARINE_PLATFORMS = withUnspecified([
    // United States
    platform('Virginia SSN', 'Virginia-class attack submarine (SSN)'),
    platform('Los Angeles SSN', 'Los Angeles-class attack submarine (SSN)'),
    platform('Seawolf SSN', 'Seawolf-class attack submarine (SSN)'),
    platform('Ohio SSBN', 'Ohio-class ballistic missile submarine (SSBN)'),
    platform('Ohio SSGN', 'Ohio-class guided missile submarine (SSGN)'),
    platform('Columbia SSBN', 'Columbia-class ballistic missile submarine (SSBN)'),
    // Russia
    platform('Borei SSBN', 'Borei-class ballistic missile submarine (SSBN)'),
    platform('Delta IV SSBN', 'Delta IV-class ballistic missile submarine (SSBN)'),
    platform('Akula SSN', 'Akula-class attack submarine (SSN)'),
    platform('Yasen SSN', 'Yasen-class attack submarine (SSN)'),
    platform('Kilo SS', 'Kilo-class diesel-electric submarine (SSK)'),
    platform('Lada SS', 'Lada-class diesel-electric submarine (SSK)'),
    platform('Improved Kilo', 'Improved Kilo-class submarine (SSK)'),
    platform('Oscar SSGN', 'Oscar-class cruise missile submarine (SSGN)'),
    platform('Sierra SSN', 'Sierra-class attack submarine (SSN)'),
    platform('Victor III SSN', 'Victor III-class attack submarine (SSN)'),
    // China
    platform('Type 094 SSBN', 'Type 094 Jin-class ballistic missile submarine (SSBN)'),
    platform('Type 096 SSBN', 'Type 096 Tang-class ballistic missile submarine (SSBN)'),
    platform('Type 093 SSN', 'Type 093 Shang-class attack submarine (SSN)'),
    platform('Type 095 SSN', 'Type 095 Sui-class attack submarine (SSN)'),
    platform('Type 039A SSK', 'Type 039A Yuan-class submarine (SSK)'),
    platform('Type 039B SSK', 'Type 039B Yuan-class submarine (SSK)'),
    platform('Type 041 SSK', 'Type 041 Zhou-class submarine (SSK)'),
    platform('Type 032 SSBN', 'Type 032 Qing-class submarine'),
    // United Kingdom
    platform('Astute SSN', 'Astute-class attack submarine (SSN)'),
    platform('Vanguard SSBN', 'Vanguard-class ballistic missile submarine (SSBN)'),
    platform('Dreadnought SSBN', 'Dreadnought-class ballistic missile submarine (SSBN)'),
    // France
    platform('Triomphant SSBN', 'Triomphant-class ballistic missile submarine (SSBN)'),
    platform('Barracuda SSN', 'Barracuda-class attack submarine (SSN)'),
    platform('Rubis SSN', 'Rubis-class attack submarine (SSN)'),
    // India
    platform('Arihant SSBN', 'Arihant-class ballistic missile submarine (SSBN)'),
    platform('Chakra SSN', 'Chakra-class attack submarine (SSN)'),
    platform('Kalvari SSK', 'Kalvari-class submarine (SSK)'),
    platform('Scorpene SSK', 'Scorpene-class submarine (SSK)'),
    // Japan
    platform('Taigei SS', 'Taigei-class submarine (SS)'),
    platform('Soryu SS', 'Soryu-class submarine (SS)'),
    platform('Oyashio SS', 'Oyashio-class submarine (SS)'),
    // South Korea
    platform('Dosan Ahn Changho SS', 'Dosan Ahn Changho-class submarine (SS)'),
    platform('Son Won-il SS', 'Son Won-il-class submarine (SS)'),
    platform('Chang Bogo SS', 'Chang Bogo-class submarine (SS)'),
    // Australia
    platform('Collins SS', 'Collins-class submarine (SSK)'),
    platform('Attack SSN', 'Attack-class submarine (SSN)'),
    // Other operators
    platform('Dolphin SS', 'Dolphin-class submarine (Israel)'),
    platform('Type 212A SS', 'Type 212A submarine (Germany)'),
    platform('Type 214 SS', 'Type 214 submarine'),
    platform('Gotland SS', 'Gotland-class submarine (Sweden)'),
    platform('A26 SS', 'A26 Blekinge-class submarine (Sweden)'),
    platform('Scorpene', 'Scorpene-class submarine (SSK)'),
    platform('Scorpene-BRA', 'Scorpene-class submarine (Brazil)'),
    platform('Scorpene-MYS', 'Scorpene-class submarine (Malaysia)'),
    platform('Scorpene-CHL', 'Scorpene-class submarine (Chile)'),
    platform('Scorpene-IND', 'Scorpene-class submarine (India)'),
    platform('Kilo-IND', 'Kilo-class submarine (India)'),
    platform('Kilo-IRN', 'Kilo-class submarine (Iran)'),
    platform('Kilo-VNM', 'Kilo-class submarine (Vietnam)'),
    platform('Kilo-ALG', 'Kilo-class submarine (Algeria)'),
    platform('Kilo-CHN', 'Kilo-class submarine (China)'),
    platform('U212A', 'Type 212A submarine'),
    platform('U212-ITA', 'Type 212A submarine (Italy)'),
    platform('U214', 'Type 214 submarine'),
    platform('U214-GRC', 'Type 214 submarine (Greece)'),
    platform('U214-PRT', 'Type 214 submarine (Portugal)'),
    platform('U214-KOR', 'Type 214 submarine (South Korea)'),
    platform('U214-TUR', 'Type 214 submarine (Turkey)'),
    platform('Dolphin', 'Dolphin-class submarine (Israel)'),
    platform('Hangor', 'Hangor-class submarine (Pakistan)'),
    platform('Agosta 90B', 'Agosta 90B-class submarine (Pakistan)'),
    platform('Nagapasa', 'Nagapasa-class submarine (Indonesia)'),
    platform('Invincible', 'Invincible-class submarine (Singapore)'),
    platform('TR-1700', 'TR-1700-class submarine (Argentina)'),
    platform('S80', 'S-80 Plus-class submarine (Spain)'),
    platform('Walrus', 'Walrus-class submarine (Netherlands)'),
    platform('Suffren', 'Suffren-class submarine (France)'),
    platform('Agosta', 'Agosta-class submarine'),
    platform('Ula', 'Ula-class submarine (Norway)'),
    platform('Kobben', 'Kobben-class submarine (Norway)'),
    platform('Orzel', 'Orzel-class submarine (Poland)'),
    platform('Kilo-RUS', 'Kilo-class submarine (Russia)'),
    platform('Improved Kilo-RUS', 'Improved Kilo-class submarine (Russia)'),
    platform('Yasen-M', 'Yasen-M-class attack submarine (SSN)'),
    platform('Borei-A', 'Borei-A-class ballistic missile submarine (SSBN)'),
    platform('Virginia Block I', 'Virginia-class Block I submarine (SSN)'),
    platform('Virginia Block II', 'Virginia-class Block II submarine (SSN)'),
    platform('Virginia Block III', 'Virginia-class Block III submarine (SSN)'),
    platform('Virginia Block IV', 'Virginia-class Block IV submarine (SSN)'),
    platform('Virginia Block V', 'Virginia-class Block V submarine (SSN)'),
])
