import {platform, withUnspecified} from './helpers.js'

export const ROTARY_WING_PLATFORMS = withUnspecified([
    // United States Army
    platform('UH-60A', 'UH-60A Black Hawk'),
    platform('UH-60L', 'UH-60L Black Hawk'),
    platform('UH-60M', 'UH-60M Black Hawk'),
    platform('UH-60V', 'UH-60V Black Hawk'),
    platform('EH-60A', 'EH-60A Black Hawk'),
    platform('MH-60K', 'MH-60K Black Hawk'),
    platform('MH-60L', 'MH-60L Black Hawk'),
    platform('MH-60M', 'MH-60M Black Hawk'),
    platform('CH-47D', 'CH-47D Chinook'),
    platform('CH-47F', 'CH-47F Chinook'),
    platform('MH-47G', 'MH-47G Chinook'),
    platform('AH-64D', 'AH-64D Apache Longbow'),
    platform('AH-64E', 'AH-64E Apache Guardian'),
    platform('AH-6M', 'AH-6M Little Bird'),
    platform('MH-6M', 'MH-6M Little Bird'),
    platform('UH-72A', 'UH-72A Lakota'),
    platform('UH-72B', 'UH-72B Lakota'),
    // United States Navy / Marines / Coast Guard
    platform('MH-60R', 'MH-60R Seahawk'),
    platform('MH-60S', 'MH-60S Seahawk'),
    platform('SH-60B', 'SH-60B Seahawk'),
    platform('SH-60F', 'SH-60F Seahawk'),
    platform('HH-60H', 'HH-60H Rescue Hawk'),
    platform('HH-60G', 'HH-60G Pave Hawk'),
    platform('HH-60W', 'HH-60W Jolly Green II'),
    platform('MH-53E', 'MH-53E Sea Dragon'),
    platform('CH-53E', 'CH-53E Super Stallion'),
    platform('CH-53K', 'CH-53K King Stallion'),
    platform('UH-1Y', 'UH-1Y Venom'),
    platform('AH-1Z', 'AH-1Z Viper'),
    platform('VH-3D', 'VH-3D Sea King'),
    platform('VH-60N', 'VH-60N White Hawk'),
    platform('VH-92A', 'VH-92A Patriot'),
    platform('TH-73A', 'TH-73A Thrasher'),
    platform('TH-57', 'TH-57 Sea Ranger'),
    platform('UH-1N', 'UH-1N Twin Huey'),
    platform('MH-139A', 'MH-139A Grey Wolf'),
    platform('TH-1H', 'TH-1H Iroquois'),
    platform('MH-60T', 'MH-60T Jayhawk'),
    platform('MH-65E', 'MH-65E Dolphin'),
    // Russia
    platform('Mi-8', 'Mil Mi-8 Hip'),
    platform('Mi-8AMT', 'Mil Mi-8AMT Hip'),
    platform('Mi-8AMTSh', 'Mil Mi-8AMTSh'),
    platform('Mi-8MTV-5', 'Mil Mi-8MTV-5 Hip'),
    platform('Mi-17', 'Mil Mi-17 Hip'),
    platform('Mi-17V-5', 'Mil Mi-17V-5 Hip'),
    platform('Mi-171', 'Mil Mi-171 Hip'),
    platform('Mi-171Sh', 'Mil Mi-171Sh'),
    platform('Mi-24', 'Mil Mi-24 Hind'),
    platform('Mi-24P', 'Mil Mi-24P Hind'),
    platform('Mi-24V', 'Mil Mi-24V Hind'),
    platform('Mi-35', 'Mil Mi-35 Hind'),
    platform('Mi-35M', 'Mil Mi-35M Hind'),
    platform('Mi-35P', 'Mil Mi-35P Hind'),
    platform('Mi-28N', 'Mil Mi-28N Havoc'),
    platform('Mi-28NM', 'Mil Mi-28NM Havoc'),
    platform('Mi-28UB', 'Mil Mi-28UB Havoc'),
    platform('Mi-26', 'Mil Mi-26 Halo'),
    platform('Mi-26T', 'Mil Mi-26T Halo'),
    platform('Mi-38T', 'Mil Mi-38T'),
    platform('Ka-27', 'Kamov Ka-27 Helix'),
    platform('Ka-28', 'Kamov Ka-28 Helix'),
    platform('Ka-29', 'Kamov Ka-29 Helix'),
    platform('Ka-31', 'Kamov Ka-31 Helix'),
    platform('Ka-52', 'Kamov Ka-52 Hokum'),
    platform('Ka-52K', 'Kamov Ka-52K Katran'),
    platform('Ka-226', 'Kamov Ka-226'),
    platform('Ansat-U', 'Kazan Ansat-U'),
    platform('Mi-2', 'Mil Mi-2 Hoplite'),
    // China
    platform('Z-8', 'Harbin Z-8'),
    platform('Z-9', 'Harbin Z-9'),
    platform('Z-9C', 'Harbin Z-9C'),
    platform('Z-10', 'CAIC Z-10'),
    platform('Z-19', 'Harbin Z-19'),
    platform('Z-20', 'Harbin Z-20'),
    platform('Z-18', 'Changhe Z-18'),
    platform('Z-18F', 'Changhe Z-18F'),
    // Europe
    platform('NH90 TTH', 'NHIndustries NH90 TTH'),
    platform('NH90 NFH', 'NHIndustries NH90 NFH'),
    platform('AW101', 'AgustaWestland AW101 Merlin'),
    platform('AW159', 'AgustaWestland AW159 Wildcat'),
    platform('AW139', 'Leonardo AW139'),
    platform('AW169', 'Leonardo AW169'),
    platform('AW109', 'Leonardo AW109'),
    platform('Tiger HAD', 'Eurocopter Tiger HAD'),
    platform('Tiger HAP', 'Eurocopter Tiger HAP'),
    platform('Tiger ARH', 'Eurocopter Tiger ARH'),
    platform('AS532', 'Eurocopter AS532 Cougar'),
    platform('EC725', 'Eurocopter EC725 Caracal'),
    platform('H145M', 'Airbus H145M'),
    platform('H225M', 'Airbus H225M Caracal'),
    platform('CH-148', 'Sikorsky CH-148 Cyclone'),
    platform('CH-149', 'AgustaWestland CH-149 Cormorant'),
    platform('Lynx AH9', 'Westland Lynx AH9'),
    platform('Super Lynx 300', 'Westland Super Lynx 300'),
    platform('Sea King Mk41', 'Westland Sea King Mk41'),
    platform('Sea King Mk48', 'Westland Sea King Mk48'),
    platform('Sea King Mk50', 'Westland Sea King Mk50'),
    // Japan / South Korea / Taiwan
    platform('UH-60J', 'Mitsubishi UH-60J'),
    platform('UH-60JA', 'Mitsubishi UH-60JA'),
    platform('SH-60K', 'Mitsubishi SH-60K'),
    platform('SH-60J', 'Mitsubishi SH-60J'),
    platform('UH-60P', 'Sikorsky UH-60P (South Korea)'),
    platform('HH-60P', 'Sikorsky HH-60P (South Korea)'),
    platform('AH-64E-KOR', 'AH-64E Apache Guardian (South Korea)'),
    platform('UH-60M-TWN', 'UH-60M Black Hawk (Taiwan)'),
    platform('AH-64E-TWN', 'AH-64E Apache Guardian (Taiwan)'),
    platform('AH-1W-TWN', 'AH-1W SuperCobra (Taiwan)'),
    platform('OH-58D-TWN', 'OH-58D Kiowa Warrior (Taiwan)'),
    // India / Middle East / other operators
    platform('Mi-17V5-IND', 'Mil Mi-17V5 (India)'),
    platform('Mi-35-IND', 'Mil Mi-35 (India)'),
    platform('AH-64E-IND', 'AH-64E Apache Guardian (India)'),
    platform('CH-47F-IND', 'CH-47F Chinook (India)'),
    platform('AH-64E-ISR', 'AH-64E Apache Guardian (Israel)'),
    platform('AH-64E-SAU', 'AH-64E Apache Guardian (Saudi Arabia)'),
    platform('AH-64E-UAE', 'AH-64E Apache Guardian (UAE)'),
    platform('AH-64E-EGY', 'AH-64E Apache Guardian (Egypt)'),
    platform('AH-64E-GBR', 'AH-64E Apache Guardian (UK)'),
    platform('CH-47F-GBR', 'CH-47F Chinook (UK)'),
    platform('CH-47F-AUS', 'CH-47F Chinook (Australia)'),
    platform('CH-47F-CAN', 'CH-47F Chinook (Canada)'),
    platform('CH-47F-NLD', 'CH-47F Chinook (Netherlands)'),
    platform('MH-60R-AUS', 'MH-60R Seahawk (Australia)'),
    platform('MH-60R-DNK', 'MH-60R Seahawk (Denmark)'),
    platform('MH-60R-NOR', 'MH-60R Seahawk (Norway)'),
    platform('MH-60R-ESP', 'MH-60R Seahawk (Spain)'),
    platform('MH-60R-IND', 'MH-60R Seahawk (India)'),
    platform('MH-60R-KOR', 'MH-60R Seahawk (South Korea)'),
    platform('MH-60R-JPN', 'MH-60R Seahawk (Japan)'),
    platform('MH-60R-GBR', 'MH-60R Seahawk (UK)'),
    platform('MH-60R-TUR', 'MH-60R Seahawk (Turkey)'),
    platform('MH-60R-GRC', 'MH-60R Seahawk (Greece)'),
    platform('MH-60R-SAU', 'MH-60R Seahawk (Saudi Arabia)'),
    platform('MH-60R-QAT', 'MH-60R Seahawk (Qatar)'),
    platform('S-70i', 'Sikorsky S-70i'),
    platform('S-70i-TUR', 'Sikorsky S-70i (Turkey)'),
    platform('S-70i-POL', 'Sikorsky S-70i (Poland)'),
    platform('S-70i-BRA', 'Sikorsky S-70i (Brazil)'),
    platform('S-92', 'Sikorsky S-92'),
    platform('UH-1H', 'Bell UH-1H Iroquois'),
    platform('AH-1F', 'Bell AH-1F Cobra'),
    platform('AH-1S', 'Bell AH-1S Cobra'),
    platform('AH-1W', 'Bell AH-1W SuperCobra'),
    platform('AH-1J', 'Bell AH-1J SeaCobra'),
    platform('OH-58D', 'Bell OH-58D Kiowa Warrior'),
    platform('Bell 412', 'Bell 412'),
    platform('Bell 212', 'Bell 212'),
    platform('AS350', 'Eurocopter AS350 Ecureuil'),
    platform('AS355', 'Eurocopter AS355 Ecureuil 2'),
])

export const UAV_PLATFORMS = withUnspecified([
    // United States
    platform('MQ-1C', 'MQ-1C Gray Eagle'),
    platform('MQ-9A', 'MQ-9A Reaper'),
    platform('MQ-9B', 'MQ-9B SkyGuardian'),
    platform('RQ-4B', 'RQ-4B Global Hawk'),
    platform('MQ-4C', 'MQ-4C Triton'),
    platform('RQ-7B', 'RQ-7B Shadow'),
    platform('RQ-11', 'RQ-11 Raven'),
    platform('RQ-20', 'RQ-20 Puma'),
    platform('RQ-21', 'RQ-21A Blackjack'),
    platform('RQ-170', 'RQ-170 Sentinel'),
    platform('MQ-25A', 'MQ-25A Stingray'),
    platform('MQ-8C', 'MQ-8C Fire Scout'),
    platform('MQ-27B', 'MQ-27B ScanEagle'),
    platform('BQM-167', 'BQM-167 Skeeter'),
    platform('QF-16', 'QF-16 Aerial Target'),
    platform('Black Hornet', 'Teledyne Black Hornet Nano'),
    platform('R80D', 'Teledyne R80D SkyRaider'),
    platform('X2D', 'Skydio X2D'),
    platform('Dzyne ULTRA', 'DZYNE ULTRA'),
    // Russia
    platform('Orlan-10', 'Orlan-10'),
    platform('Forpost-R', 'Forpost-R'),
    platform('Altius', 'Sokol Altius'),
    platform('Okhotnik', 'Sukhoi S-70 Okhotnik'),
    platform('Lancet', 'ZALA Lancet'),
    platform('Kub-BLA', 'ZALA Kub-BLA'),
    platform('Orion', 'Kronshtadt Orion'),
    platform('Inokhodets', 'Inokhodets'),
    // China
    platform('WZ-7', 'Guizhou WZ-7 Soaring Dragon'),
    platform('WZ-8', 'WZ-8'),
    platform('WZ-10', 'WZ-10'),
    platform('GJ-11', 'Hongdu GJ-11'),
    platform('CH-4', 'CASC CH-4'),
    platform('CH-5', 'CASC CH-5'),
    platform('Wing Loong I', 'Chengdu Wing Loong I'),
    platform('Wing Loong II', 'Chengdu Wing Loong II'),
    platform('Wing Loong III', 'Chengdu Wing Loong III'),
    platform('Rainbow-4', 'CASC Rainbow-4'),
    platform('Rainbow-5', 'CASC Rainbow-5'),
    platform('BZK-005', 'BZK-005'),
    platform('ASN-209', 'ASN-209'),
    // Turkey
    platform('Bayraktar TB2', 'Bayraktar TB2'),
    platform('Bayraktar Akıncı', 'Bayraktar Akıncı'),
    platform('Bayraktar Kızılelma', 'Bayraktar Kızılelma'),
    platform('Anka', 'TAI Anka'),
    platform('Aksungur', 'TAI Aksungur'),
    // Israel
    platform('Hermes 450', 'Elbit Hermes 450'),
    platform('Hermes 900', 'Elbit Hermes 900'),
    platform('Heron', 'IAI Heron'),
    platform('Heron TP', 'IAI Heron TP'),
    platform('Harop', 'IAI Harop'),
    platform('Harpy', 'IAI Harpy'),
    platform('Eitan', 'IAI Eitan'),
    // Iran
    platform('Shahed-136', 'Shahed-136'),
    platform('Shahed-131', 'Shahed-131'),
    platform('Mohajer-6', 'Mohajer-6'),
    platform('Ababil-3', 'Ababil-3'),
    // Europe / NATO operators
    platform('Watchkeeper', 'Thales Watchkeeper WK450'),
    platform('Eurodrone', 'Eurodrone'),
    platform('MQ-9A-GBR', 'MQ-9A Reaper (UK)'),
    platform('MQ-9B-GBR', 'MQ-9B Protector (UK)'),
    platform('MQ-9A-FRA', 'MQ-9A Reaper (France)'),
    platform('MQ-9A-ITA', 'MQ-9A Reaper (Italy)'),
    platform('MQ-9A-ESP', 'MQ-9A Reaper (Spain)'),
    platform('MQ-9A-NLD', 'MQ-9A Reaper (Netherlands)'),
    platform('MQ-9A-DEU', 'MQ-9A Reaper (Germany)'),
    platform('MQ-9A-POL', 'MQ-9A Reaper (Poland)'),
    platform('MQ-9A-AUS', 'MQ-9A Reaper (Australia)'),
    platform('MQ-9B-IND', 'MQ-9B SeaGuardian (India)'),
    platform('MQ-9B-JPN', 'MQ-9B SeaGuardian (Japan)'),
    platform('MQ-9B-CAN', 'MQ-9B SkyGuardian (Canada)'),
    platform('MQ-9B-BEL', 'MQ-9B SkyGuardian (Belgium)'),
    // Other export operators
    platform('Bayraktar TB2-UKR', 'Bayraktar TB2 (Ukraine)'),
    platform('Bayraktar TB2-POL', 'Bayraktar TB2 (Poland)'),
    platform('Bayraktar TB2-ROU', 'Bayraktar TB2 (Romania)'),
    platform('Bayraktar TB2-ETH', 'Bayraktar TB2 (Ethiopia)'),
    platform('Bayraktar TB2-LBY', 'Bayraktar TB2 (Libya)'),
    platform('Bayraktar TB2-AZE', 'Bayraktar TB2 (Azerbaijan)'),
    platform('Wing Loong II-EGY', 'Wing Loong II (Egypt)'),
    platform('Wing Loong II-UAE', 'Wing Loong II (UAE)'),
    platform('Wing Loong II-SAU', 'Wing Loong II (Saudi Arabia)'),
    platform('CH-4-IRQ', 'CASC CH-4 (Iraq)'),
    platform('CH-4-PAK', 'CASC CH-4 (Pakistan)'),
    platform('CH-4-MYS', 'CASC CH-4 (Malaysia)'),
    platform('CH-4-NGA', 'CASC CH-4 (Nigeria)'),
    platform('Hermes 900-MEX', 'Hermes 900 (Mexico)'),
    platform('Hermes 900-BRA', 'Hermes 900 (Brazil)'),
    platform('Hermes 900-CHL', 'Hermes 900 (Chile)'),
    platform('Hermes 900-COL', 'Hermes 900 (Colombia)'),
    platform('Hermes 900-PHL', 'Hermes 900 (Philippines)'),
    platform('Hermes 900-THA', 'Hermes 900 (Thailand)'),
    platform('Hermes 900-SGP', 'Hermes 900 (Singapore)'),
    platform('Hermes 900-IND', 'Hermes 900 (India)'),
    platform('Hermes 900-ISR', 'Hermes 900 (Israel)'),
    platform('Hermes 900-CZE', 'Hermes 900 (Czech Republic)'),
    platform('Hermes 900-SUI', 'Hermes 900 (Switzerland)'),
    platform('Hermes 900-GBR', 'Hermes 900 (UK)'),
    platform('Hermes 900-AUS', 'Hermes 900 (Australia)'),
    platform('Hermes 900-CAN', 'Hermes 900 (Canada)'),
    platform('Hermes 900-ICE', 'Hermes 900 (Iceland)'),
    platform('Hermes 900-ECU', 'Hermes 900 (Ecuador)'),
    platform('Hermes 900-URY', 'Hermes 900 (Uruguay)'),
    platform('Hermes 900-ARG', 'Hermes 900 (Argentina)'),
    platform('Hermes 900-MAR', 'Hermes 900 (Morocco)'),
    platform('Hermes 900-ALG', 'Hermes 900 (Algeria)'),
    platform('Hermes 900-EGY', 'Hermes 900 (Egypt)'),
    platform('Hermes 900-KEN', 'Hermes 900 (Kenya)'),
    platform('Hermes 900-NGA', 'Hermes 900 (Nigeria)'),
    platform('Hermes 900-ZAF', 'Hermes 900 (South Africa)'),
])

export const VSTOL_PLATFORMS = withUnspecified([
    platform('AV-8B', 'AV-8B Harrier II'),
    platform('AV-8B+', 'AV-8B+ Harrier II Plus'),
    platform('F-35B', 'F-35B Lightning II'),
    platform('MV-22B', 'MV-22B Osprey'),
    platform('CV-22B', 'CV-22B Osprey'),
    platform('CMV-22B', 'CMV-22B Osprey'),
    platform('F-35B-GBR', 'F-35B Lightning II (UK)'),
    platform('F-35B-ITA', 'F-35B Lightning II (Italy)'),
    platform('F-35B-JPN', 'F-35B Lightning II (Japan)'),
    platform('F-35B-SGP', 'F-35B Lightning II (Singapore)'),
])

export const ASW_PLATFORMS = withUnspecified([
    platform('SH-60B', 'SH-60B Seahawk'),
    platform('SH-60F', 'SH-60F Seahawk'),
    platform('MH-60R', 'MH-60R Seahawk'),
    platform('MH-60S', 'MH-60S Seahawk'),
    platform('MH-53E', 'MH-53E Sea Dragon'),
    platform('Ka-27', 'Kamov Ka-27 Helix'),
    platform('Ka-28', 'Kamov Ka-28 Helix'),
    platform('Ka-29', 'Kamov Ka-29 Helix'),
    platform('Ka-31', 'Kamov Ka-31 Helix'),
    platform('Ka-52K', 'Kamov Ka-52K Katran'),
    platform('AW101 ASW', 'AgustaWestland AW101 Merlin ASW'),
    platform('NH90 NFH', 'NHIndustries NH90 NFH'),
    platform('Sea King Mk50', 'Westland Sea King Mk50 ASW'),
    platform('Z-18F', 'Changhe Z-18F'),
    platform('Z-9C', 'Harbin Z-9C'),
    platform('CH-148', 'Sikorsky CH-148 Cyclone'),
    platform('AW159 ASW', 'AgustaWestland AW159 Wildcat ASW'),
    platform('Super Lynx 300', 'Westland Super Lynx 300 ASW'),
    platform('MH-60R-AUS', 'MH-60R Seahawk (Australia)'),
    platform('MH-60R-DNK', 'MH-60R Seahawk (Denmark)'),
    platform('MH-60R-NOR', 'MH-60R Seahawk (Norway)'),
    platform('MH-60R-ESP', 'MH-60R Seahawk (Spain)'),
    platform('MH-60R-IND', 'MH-60R Seahawk (India)'),
    platform('MH-60R-KOR', 'MH-60R Seahawk (South Korea)'),
    platform('MH-60R-JPN', 'MH-60R Seahawk (Japan)'),
    platform('MH-60R-GBR', 'MH-60R Seahawk (UK)'),
    platform('MH-60R-TUR', 'MH-60R Seahawk (Turkey)'),
    platform('MH-60R-GRC', 'MH-60R Seahawk (Greece)'),
    platform('MH-60R-SAU', 'MH-60R Seahawk (Saudi Arabia)'),
    platform('MH-60R-QAT', 'MH-60R Seahawk (Qatar)'),
])
