import {platform, withUnspecified} from './helpers.js'

export const TANKER_PLATFORMS = withUnspecified([
    platform('KC-135R', 'KC-135R Stratotanker'),
    platform('KC-135T', 'KC-135T Stratotanker'),
    platform('KC-46A', 'KC-46A Pegasus'),
    platform('KC-10A', 'KC-10A Extender'),
    platform('KC-130J', 'KC-130J Super Hercules'),
    platform('KC-130T', 'KC-130T Hercules'),
    platform('KC-390', 'Embraer KC-390 Millennium'),
    platform('Il-78', 'Ilyushin Il-78 Midas'),
    platform('Il-78M', 'Ilyushin Il-78M Midas'),
    platform('Il-78M-90A', 'Ilyushin Il-78M-90A'),
    platform('YY-20', 'Xian YY-20'),
    platform('YY-20A', 'Xian YY-20A'),
    platform('YY-20B', 'Xian YY-20B'),
    platform('H-6U', 'Xian H-6U Tanker'),
    platform('Il-78-CN', 'Ilyushin Il-78 (China)'),
    platform('A330 MRTT', 'Airbus A330 MRTT'),
    platform('A330 MRTT-AUS', 'A330 MRTT (Australia)'),
    platform('A330 MRTT-GBR', 'A330 MRTT (UK)'),
    platform('A330 MRTT-FRA', 'A330 MRTT (France)'),
    platform('A330 MRTT-SAU', 'A330 MRTT (Saudi Arabia)'),
    platform('A330 MRTT-SGP', 'A330 MRTT (Singapore)'),
    platform('A330 MRTT-UAE', 'A330 MRTT (UAE)'),
    platform('A330 MRTT-KOR', 'A330 MRTT (South Korea)'),
    platform('KC-767', 'Boeing KC-767'),
    platform('KC-767-JPN', 'Boeing KC-767 (Japan)'),
    platform('KC-767-ITA', 'Boeing KC-767 (Italy)'),
    platform('KC-46-JPN', 'KC-46A Pegasus (Japan)'),
    platform('KC-30A', 'Airbus KC-30A (Australia)'),
    platform('Il-78-IND', 'Ilyushin Il-78 (India)'),
    platform('MQ-25A', 'Boeing MQ-25A Stingray'),
])

export const AWACS_PLATFORMS = withUnspecified([
    platform('E-3B', 'E-3B Sentry'),
    platform('E-3G', 'E-3G Sentry'),
    platform('E-7A', 'E-7A Wedgetail'),
    platform('E-7A-GBR', 'E-7A Wedgetail (UK)'),
    platform('E-7A-TUR', 'E-7T Peace Eagle (Turkey)'),
    platform('E-7A-KOR', 'E-7A Wedgetail (South Korea)'),
    platform('E-2C', 'E-2C Hawkeye'),
    platform('E-2D', 'E-2D Advanced Hawkeye'),
    platform('A-50', 'Beriev A-50 Mainstay'),
    platform('A-50U', 'Beriev A-50U Mainstay'),
    platform('A-100', 'Beriev A-100 Premier'),
    platform('KJ-2000', 'KJ-2000 Mainring'),
    platform('KJ-200', 'KJ-200 Moth'),
    platform('KJ-500', 'KJ-500'),
    platform('KJ-600', 'KJ-600'),
    platform('KJ-3000', 'KJ-3000'),
    platform('Saab 340 AEW', 'Saab 340 AEW&C'),
    platform('Saab 2000 AEW', 'Saab 2000 Erieye'),
    platform('Erieye', 'Saab Erieye'),
    platform('E-2K', 'E-2K Hawkeye (Taiwan)'),
    platform('Ka-31', 'Kamov Ka-31 Helix'),
    platform('Ka-31-RUS', 'Kamov Ka-31 (Russia)'),
    platform('Ka-31-CHN', 'Kamov Ka-31 (China)'),
    platform('Ka-31-IND', 'Kamov Ka-31 (India)'),
    platform('E-767', 'Boeing E-767 AWACS (Japan)'),
    platform('G550 CAEW', 'Gulfstream G550 CAEW (Israel)'),
    platform('G550 CAEW-ITA', 'Gulfstream G550 CAEW (Italy)'),
    platform('G550 CAEW-SGP', 'Gulfstream G550 CAEW (Singapore)'),
    platform('Falcon 900 ESM', 'Dassault Falcon 900 ESM'),
    platform('E-6B', 'E-6B Mercury'),
])

export const PATROL_PLATFORMS = withUnspecified([
    platform('P-8A', 'P-8A Poseidon'),
    platform('P-8I', 'P-8I Neptune (India)'),
    platform('P-3C', 'P-3C Orion'),
    platform('P-3C-JPN', 'P-3C Orion (Japan)'),
    platform('P-3C-NOR', 'P-3C Orion (Norway)'),
    platform('P-3C-TWN', 'P-3C Orion (Taiwan)'),
    platform('P-1', 'Kawasaki P-1'),
    platform('Tu-142', 'Tupolev Tu-142 Bear'),
    platform('Il-38', 'Ilyushin Il-38 May'),
    platform('Il-38N', 'Ilyushin Il-38N May'),
    platform('Be-12', 'Beriev Be-12 Mail'),
    platform('Be-200', 'Beriev Be-200 Altair'),
    platform('CL-604 MSA', 'Bombardier CL-604 MSA'),
    platform('HC-144B', 'HC-144B Ocean Sentry'),
    platform('CN-235 MPA', 'CASA CN-235 MPA'),
    platform('C-295 MPA', 'Airbus C-295 MPA'),
    platform('ATR 72 MPA', 'ATR 72 MPA'),
    platform('Saab 340 MPA', 'Saab 340 MPA'),
    platform('Dornier 228', 'Dornier 228 MPA'),
    platform('BN-2 Islander', 'Britten-Norman BN-2 Islander'),
    platform('P-72', 'ATR P-72A (Italy)'),
    platform('P-3K2', 'P-3K2 Orion (New Zealand)'),
    platform('P-3B', 'P-3B Orion (Brazil)'),
    platform('P-3C-CHL', 'P-3C Orion (Chile)'),
    platform('P-3C-ARG', 'P-3 Orion (Argentina)'),
    platform('P-3C-THA', 'P-3 Orion (Thailand)'),
    platform('P-3C-KOR', 'P-3C Orion (South Korea)'),
    platform('P-3C-GER', 'P-3C Orion (Germany)'),
    platform('P-3C-GRC', 'P-3B Orion (Greece)'),
    platform('P-3C-POR', 'P-3C Orion (Portugal)'),
    platform('P-3C-SPA', 'P-3 Orion (Spain)'),
    platform('P-9A', 'Bombardier P-9A Pale Ale'),
])

export const RECON_PLATFORMS = withUnspecified([
    platform('U-2S', 'U-2S Dragon Lady'),
    platform('TU-2S', 'TU-2S Dragon Lady'),
    platform('RC-135S', 'RC-135S Cobra Ball'),
    platform('RC-135U', 'RC-135U Combat Sent'),
    platform('RC-135V', 'RC-135V Rivet Joint'),
    platform('RC-135W', 'RC-135W Rivet Joint'),
    platform('RQ-4B', 'RQ-4B Global Hawk'),
    platform('MQ-4C', 'MQ-4C Triton'),
    platform('EP-3E', 'EP-3E Aries II'),
    platform('WC-135R', 'WC-135R Constant Phoenix'),
    platform('U-28A', 'U-28A Draco'),
    platform('Tu-214R', 'Tupolev Tu-214R'),
    platform('Tu-214ON', 'Tupolev Tu-214ON'),
    platform('Il-20', 'Ilyushin Il-20 Coot'),
    platform('Il-22', 'Ilyushin Il-22 Coot-B'),
    platform('An-30', 'Antonov An-30 Clank'),
    platform('J-8FR', 'Shenyang J-8FR'),
    platform('JZ-8F', 'Xian JZ-8F'),
    platform('Tu-154M-LK-1', 'Tu-154M-LK-1'),
    platform('Gulfstream G550 ISR', 'Gulfstream G550 ISR'),
    platform('Bombardier Global 6000', 'Bombardier Global 6000 ISR'),
    platform('CL-650 ARTEMIS', 'Bombardier CL-650 ARTEMIS'),
    platform('RC-12', 'Beechcraft RC-12 Guardrail'),
    platform('EO-5', 'de Havilland Canada EO-5'),
    platform('E-9A', 'de Havilland Canada E-9A Widget'),
    platform('RQ-170', 'RQ-170 Sentinel'),
    platform('RQ-180', 'RQ-180'),
    platform('WZ-7', 'Guizhou WZ-7 Soaring Dragon'),
    platform('WZ-8', 'WZ-8'),
    platform('WZ-10', 'WZ-10'),
])

export const PHOTO_RECON_PLATFORMS = withUnspecified([
    platform('U-2S', 'U-2S Dragon Lady'),
    platform('RQ-4B', 'RQ-4B Global Hawk'),
    platform('MQ-4C', 'MQ-4C Triton'),
    platform('RC-135', 'RC-135 Rivet Joint'),
    platform('J-8FR', 'Shenyang J-8FR'),
    platform('Mirage IIIR', 'Dassault Mirage IIIR'),
    platform('RF-4E', 'RF-4E Phantom II'),
    platform('RF-16', 'RF-16 Fighting Falcon (Taiwan)'),
    platform('Su-24MR', 'Su-24MR Fencer'),
    platform('Tu-22R', 'Tu-22R Blinder'),
    platform('An-30', 'Antonov An-30 Clank'),
    platform('WZ-7', 'Guizhou WZ-7 Soaring Dragon'),
])

export const JAMMER_PLATFORMS = withUnspecified([
    platform('EA-18G', 'EA-18G Growler'),
    platform('EA-37B', 'EA-37B Compass Call'),
    platform('EC-130H', 'EC-130H Compass Call'),
    platform('EC-37B', 'EC-37B Compass Call'),
    platform('An-12PP', 'Antonov An-12PP'),
    platform('Il-22PP', 'Ilyushin Il-22PP'),
    platform('J-16D', 'Shenyang J-16D'),
    platform('Y-8GX', 'Shaanxi Y-8GX'),
    platform('Y-9GX', 'Shaanxi Y-9GX'),
    platform('Tu-214PU', 'Tupolev Tu-214PU'),
    platform('EF-18M', 'EF-18M Growler (Spain)'),
    platform('EA-6B', 'EA-6B Prowler (retiring)'),
])

export const COMMAND_POST_PLATFORMS = withUnspecified([
    platform('E-4B', 'E-4B NAOC'),
    platform('E-6B', 'E-6B Mercury'),
    platform('E-11A', 'E-11A BACN'),
    platform('Il-80', 'Ilyushin Il-80 Maxdome'),
    platform('Il-82', 'Ilyushin Il-82'),
    platform('Il-18V', 'Ilyushin Il-18V'),
    platform('Tu-214PU', 'Tupolev Tu-214PU'),
    platform('Tu-214SR', 'Tupolev Tu-214SR'),
    platform('VC-25A', 'VC-25A Air Force One'),
    platform('C-32A', 'C-32A Air Force Two'),
    platform('C-37A', 'C-37A Gulfstream V'),
    platform('C-37B', 'C-37B Gulfstream G550'),
])

export const PASSENGER_PLATFORMS = withUnspecified([
    platform('C-40B', 'C-40B Clipper'),
    platform('C-40C', 'C-40C Clipper'),
    platform('C-21A', 'C-21A Learjet'),
    platform('C-37A', 'C-37A Gulfstream V'),
    platform('C-37B', 'C-37B Gulfstream G550'),
    platform('C-32A', 'C-32A'),
    platform('VC-25A', 'VC-25A'),
    platform('An-148 VIP', 'Antonov An-148 VIP'),
    platform('Il-62M', 'Ilyushin Il-62M'),
    platform('Tu-154B', 'Tupolev Tu-154B'),
    platform('Gulfstream G550', 'Gulfstream G550'),
    platform('Gulfstream G650', 'Gulfstream G650'),
    platform('Falcon 7X', 'Dassault Falcon 7X'),
    platform('Falcon 900', 'Dassault Falcon 900'),
    platform('Challenger 600', 'Bombardier Challenger 600'),
    platform('Global Express', 'Bombardier Global Express'),
    platform('C-20G', 'C-20G Grey Ghost'),
    platform('UC-35', 'Cessna UC-35 Citation'),
])

export const ELECTRONIC_ATTACK_PLATFORMS = withUnspecified([
    platform('EA-18G', 'EA-18G Growler'),
    platform('EA-37B', 'EA-37B Compass Call'),
    platform('EC-130H', 'EC-130H Compass Call'),
    platform('J-16D', 'Shenyang J-16D'),
    platform('Il-22PP', 'Ilyushin Il-22PP'),
    platform('An-12PP', 'Antonov An-12PP'),
    platform('EF-18M', 'EF-18M Growler (Spain)'),
])
