import {platform, withUnspecified} from './helpers.js'

export const TRAINER_PLATFORMS = withUnspecified([
    platform('T-6A', 'T-6A Texan II'),
    platform('T-6B', 'T-6B Texan II'),
    platform('T-6D', 'T-6D Texan II'),
    platform('T-6C', 'T-6C Texan II'),
    platform('CT-156', 'CT-156 Harvard II'),
    platform('T-7A', 'T-7A Red Hawk'),
    platform('T-38A', 'T-38A Talon'),
    platform('T-38C', 'T-38C Talon'),
    platform('AT-38B', 'AT-38B Talon'),
    platform('T-1A', 'T-1A Jayhawk'),
    platform('T-41', 'T-41 Mescalero'),
    platform('T-45C', 'T-45C Goshawk'),
    platform('T-54A', 'T-54A Marlin II'),
    platform('T-44C', 'T-44C Pegasus'),
    platform('L-39', 'Aero L-39 Albatros'),
    platform('L-39ZA', 'Aero L-39ZA Albatros'),
    platform('L-159', 'Aero L-159 Alca'),
    platform('Yak-130', 'Yakovlev Yak-130'),
    platform('Yak-152', 'Yakovlev Yak-152'),
    platform('JL-8', 'Hongdu JL-8'),
    platform('JL-9', 'Guizhou JL-9'),
    platform('JL-10', 'Hongdu JL-10'),
    platform('L-15', 'Hongdu L-15 Falcon'),
    platform('KAI T-50', 'KAI T-50 Golden Eagle'),
    platform('PC-21', 'Pilatus PC-21'),
    platform('PC-7', 'Pilatus PC-7'),
    platform('PC-9', 'Pilatus PC-9'),
    platform('PC-9M', 'Pilatus PC-9M'),
    platform('T-34C', 'T-34C Turbo Mentor'),
    platform('Hawk T1', 'BAE Hawk T1'),
    platform('Hawk T2', 'BAE Hawk T2'),
    platform('Hawk 127', 'BAE Hawk 127'),
    platform('Hawk 128', 'BAE Hawk 128'),
    platform('Hawk 132', 'BAE Hawk 132'),
    platform('Hawk 165', 'BAE Hawk 165'),
    platform('Hawk 167', 'BAE Hawk 167'),
    platform('M-346', 'Leonardo M-346 Master'),
    platform('T-346A', 'Leonardo T-346A Master'),
    platform('Alpha Jet', 'Dassault/Dornier Alpha Jet'),
    platform('MB-339', 'Aermacchi MB-339'),
    platform('MB-339CD', 'Aermacchi MB-339CD'),
    platform('T-4', 'Kawasaki T-4'),
    platform('T-5', 'Fuji T-5'),
    platform('T-7', 'Fuji T-7'),
    platform('KT-1', 'KAI KT-1 Woongbi'),
    platform('Diamond DA42', 'Diamond DA42'),
    platform('EMB-312', 'Embraer EMB-312 Tucano'),
    platform('A-29', 'Embraer A-29 Super Tucano'),
    platform('TG-15A', 'TG-15A Glider'),
    platform('TG-16A', 'TG-16A Glider'),
    platform('TH-67', 'TH-67 Creek'),
    platform('TH-73A', 'TH-73A Thrasher'),
    platform('TH-57', 'TH-57 Sea Ranger'),
    platform('TH-1H', 'TH-1H Iroquois'),
    platform('Tu-134UBL', 'Tu-134UBL'),
    platform('Su-25UTG', 'Su-25UTG Frogfoot'),
    platform('Mirage 2000B', 'Dassault Mirage 2000B'),
    platform('Mirage 2000D', 'Dassault Mirage 2000D'),
    platform('F-16D-BLK', 'F-16D Block 50 (conversion trainer)'),
    platform('F-15D', 'F-15D Eagle'),
    platform('F/A-18D', 'F/A-18D Hornet'),
    platform('F/A-18F', 'F/A-18F Super Hornet'),
    platform('F-35B', 'F-35B Lightning II'),
    platform('F-35C', 'F-35C Lightning II'),
    platform('J-10S', 'Chengdu J-10S'),
    platform('J-15S', 'Shenyang J-15S'),
    platform('J-20S', 'Chengdu J-20S'),
    platform('Su-27UB', 'Su-27UB Flanker'),
    platform('Su-30MKK', 'Su-30MKK Flanker'),
    platform('MiG-29UB', 'MiG-29UB Fulcrum'),
    platform('MiG-35UB', 'MiG-35UB Fulcrum'),
    platform('L-39C', 'Aero L-39C Albatros'),
    platform('L-39NG', 'Aero L-39NG Albatros'),
    platform('PC-12', 'Pilatus PC-12'),
    platform('PC-24', 'Pilatus PC-24'),
    platform('T-53A', 'Cirrus T-53A Kadet II'),
    platform('T-51A', 'Cessna T-51A'),
    platform('UV-18B', 'UV-18B Twin Otter'),
    platform('NU-1B', 'NU-1B Otter'),
    platform('U-6A', 'U-6A Beaver'),
    platform('X-26A', 'X-26A Frigate Glider'),
])
